# Generated by Django 5.0.1 on 2025-12-13 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='google_review_url',
            field=models.URLField(blank=True, help_text='Google Business Review URL for this branch', max_length=500, null=True),
        ),
    ]
