# Generated by Django 5.0.1 on 2026-02-03 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0002_branch_google_review_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceBay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('bay_type', models.CharField(choices=[('washing', 'Washing Bay'), ('detailing', 'Detailing Bay'), ('drying', 'Drying Area'), ('inspection', 'Inspection Bay'), ('other', 'Other')], default='detailing', max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bays', to='branches.branch')),
            ],
            options={
                'verbose_name': 'Service Bay',
                'verbose_name_plural': 'Service Bays',
                'db_table': 'service_bays',
                'ordering': ['branch', 'name'],
                'unique_together': {('branch', 'name')},
            },
        ),
    ]
