# Generated by Django 5.0.1 on 2026-02-06 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0003_servicebay'),
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='servicebay',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='branch',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='companies.company'),
        ),
        migrations.AddField(
            model_name='servicebay',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_bays', to='companies.company'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='code',
            field=models.CharField(help_text='Unique branch code (e.g., DT001)', max_length=20),
        ),
        migrations.AlterField(
            model_name='branch',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='branch',
            unique_together={('company', 'code'), ('company', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='servicebay',
            unique_together={('company', 'branch', 'name')},
        ),
    ]
