# Generated by Django 5.2.12 on 2026-03-10 09:14

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_number', models.CharField(help_text="Recipient's phone number", max_length=20)),
                ('message_type', models.CharField(choices=[('text', 'Text'), ('template', 'Template'), ('image', 'Image'), ('document', 'Document'), ('audio', 'Audio'), ('video', 'Video'), ('sticker', 'Sticker'), ('location', 'Location'), ('contacts', 'Contacts'), ('interactive', 'Interactive')], default='text', max_length=20)),
                ('message_content', models.TextField(blank=True, help_text='Text content for the message', null=True)),
                ('template_name', models.CharField(blank=True, max_length=100, null=True)),
                ('template_params', models.JSONField(blank=True, help_text='JSON object of template parameters', null=True)),
                ('media_file', models.FileField(blank=True, help_text='Media file to be sent', null=True, upload_to='scheduled_media/')),
                ('scheduled_at', models.DateTimeField(help_text='The date and time to send the message')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Scheduled Message',
                'verbose_name_plural': 'Scheduled Messages',
                'ordering': ['scheduled_at'],
            },
        ),
        migrations.CreateModel(
            name='WhatsAppMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20)),
                ('message_type', models.CharField(choices=[('text', 'Text'), ('template', 'Template'), ('image', 'Image'), ('document', 'Document'), ('audio', 'Audio'), ('video', 'Video'), ('sticker', 'Sticker'), ('location', 'Location'), ('contacts', 'Contacts'), ('interactive', 'Interactive')], max_length=20)),
                ('message_content', models.TextField(blank=True, null=True)),
                ('template_name', models.CharField(blank=True, max_length=100, null=True)),
                ('media', models.FileField(blank=True, help_text='Media file to be sent', null=True, upload_to='whatsapp_media/')),
                ('message_id', models.CharField(blank=True, help_text='WhatsApp message ID for tracking', max_length=255, null=True)),
                ('frontend_id', models.CharField(blank=True, help_text='Frontend message ID for status updates', max_length=255, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('read', 'Read'), ('failed', 'Failed'), ('received', 'Received')], default='pending', max_length=20)),
                ('is_read', models.BooleanField(default=False)),
                ('status_updated_at', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_whatsapp_messages', to=settings.AUTH_USER_MODEL)),
                ('reply_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='whatsapp.whatsappmessage')),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_whatsapp_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
