# Generated by Django 5.2.12 on 2026-03-14 11:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workspace',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Name of the external system or CRM (e.g., AutoAICare)', max_length=255)),
                ('api_key', models.CharField(blank=True, help_text='Generated API Key for this workspace', max_length=64, unique=True)),
                ('api_secret', models.CharField(blank=True, help_text='Generated API Secret for this workspace', max_length=64)),
                ('webhook_url', models.URLField(blank=True, help_text='URL to receive incoming WhatsApp messages and status updates', null=True)),
                ('webhook_active', models.BooleanField(default=True, help_text='Whether to send webhooks to the URL')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
