# Generated by Django 5.2.12 on 2026-04-06 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatassignment',
            name='branch_id',
            field=models.CharField(blank=True, db_index=True, help_text='CRM Branch ID', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='branch_id',
            field=models.CharField(blank=True, db_index=True, help_text='CRM Branch ID', max_length=50, null=True),
        ),
    ]
