# Generated by Django 5.0.1 on 2026-01-31 10:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0002_branch_google_review_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('source_type', models.CharField(choices=[('website', 'Website'), ('walk_in', 'Walk-in'), ('phone', 'Phone Call'), ('referral', 'Referral'), ('social_media', 'Social Media'), ('google_ads', 'Google Ads'), ('facebook_ads', 'Facebook Ads'), ('email_campaign', 'Email Campaign'), ('event', 'Event/Exhibition'), ('other', 'Other')], max_length=30)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('cost_per_lead', models.DecimalField(decimal_places=2, default=0, help_text='Average cost per lead from this source', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Lead Source',
                'verbose_name_plural': 'Lead Sources',
                'db_table': 'lead_sources',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('company', models.CharField(blank=True, help_text='For corporate leads', max_length=200)),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('qualified', 'Qualified'), ('proposal_sent', 'Proposal Sent'), ('negotiation', 'Negotiation'), ('won', 'Won (Converted)'), ('lost', 'Lost'), ('on_hold', 'On Hold')], default='new', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10)),
                ('score', models.IntegerField(default=0, help_text='Lead quality score (0-100)')),
                ('interested_services', models.TextField(blank=True, help_text='Services the lead is interested in')),
                ('vehicle_info', models.TextField(blank=True, help_text='Vehicle details if provided')),
                ('budget_range', models.CharField(blank=True, max_length=100)),
                ('expected_close_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('converted_to_customer', models.BooleanField(default=False)),
                ('converted_at', models.DateTimeField(blank=True, null=True)),
                ('conversion_value', models.DecimalField(blank=True, decimal_places=2, help_text='First booking value', max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_contacted_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional lead information')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_leads', to=settings.AUTH_USER_MODEL)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='branches.branch')),
                ('source', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='leads.leadsource')),
            ],
            options={
                'verbose_name': 'Lead',
                'verbose_name_plural': 'Leads',
                'db_table': 'leads',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LeadConversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.IntegerField(help_text='ID of the customer created from this lead')),
                ('booking_id', models.IntegerField(blank=True, help_text='ID of the first booking', null=True)),
                ('converted_at', models.DateTimeField()),
                ('conversion_value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('conversion_days', models.IntegerField(help_text='Days from lead creation to conversion')),
                ('lead', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='conversion', to='leads.lead')),
            ],
            options={
                'verbose_name': 'Lead Conversion',
                'verbose_name_plural': 'Lead Conversions',
                'db_table': 'lead_conversions',
                'ordering': ['-converted_at'],
            },
        ),
        migrations.CreateModel(
            name='LeadScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('factors', models.JSONField(default=dict, help_text='Factors contributing to the score')),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score_history', to='leads.lead')),
            ],
            options={
                'verbose_name': 'Lead Score',
                'verbose_name_plural': 'Lead Scores',
                'db_table': 'lead_scores',
                'ordering': ['-calculated_at'],
            },
        ),
        migrations.CreateModel(
            name='LeadActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('call_outbound', 'Outbound Call'), ('call_inbound', 'Inbound Call'), ('email_sent', 'Email Sent'), ('email_received', 'Email Received'), ('sms_sent', 'SMS Sent'), ('whatsapp_sent', 'WhatsApp Sent'), ('meeting', 'Meeting'), ('site_visit', 'Site Visit'), ('proposal_sent', 'Proposal Sent'), ('follow_up', 'Follow-up'), ('note_added', 'Note Added'), ('status_changed', 'Status Changed')], max_length=30)),
                ('description', models.TextField()),
                ('outcome', models.CharField(blank=True, help_text='Result of the activity', max_length=200)),
                ('duration_minutes', models.IntegerField(blank=True, null=True)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_activities_created', to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='leads.lead')),
            ],
            options={
                'verbose_name': 'Lead Activity',
                'verbose_name_plural': 'Lead Activities',
                'db_table': 'lead_activities',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['lead', '-created_at'], name='lead_activi_lead_id_d58c46_idx'), models.Index(fields=['activity_type', '-created_at'], name='lead_activi_activit_512740_idx')],
            },
        ),
        migrations.CreateModel(
            name='LeadFollowUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_date', models.DateTimeField()),
                ('task', models.TextField(help_text='What needs to be done')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('overdue', 'Overdue')], default='pending', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_followups', to=settings.AUTH_USER_MODEL)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_followups', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_followups', to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follow_ups', to='leads.lead')),
            ],
            options={
                'verbose_name': 'Lead Follow-up',
                'verbose_name_plural': 'Lead Follow-ups',
                'db_table': 'lead_follow_ups',
                'ordering': ['due_date'],
                'indexes': [models.Index(fields=['status', 'due_date'], name='lead_follow_status_e5289b_idx'), models.Index(fields=['assigned_to', 'status'], name='lead_follow_assigne_d5c356_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['status', '-created_at'], name='leads_status_dcd0ad_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['assigned_to', 'status'], name='leads_assigne_e66f0c_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['source', '-created_at'], name='leads_source__29be78_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['-score'], name='leads_score_80ceed_idx'),
        ),
    ]
