# Generated by Django 5.0.1 on 2026-02-11 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_lead_company_ref_leadsource_company'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lead',
            old_name='company',
            new_name='organization',
        ),
        migrations.RenameField(
            model_name='lead',
            old_name='company_ref',
            new_name='company',
        ),
    ]
