# Generated by Django 5.0.1 on 2026-02-15 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_companysettings_whatsapp_mode'),
        ('leads', '0004_alter_lead_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadsource',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='leadsource',
            unique_together={('company', 'name')},
        ),
    ]
