# Generated by Django 5.0.1 on 2026-02-16 11:28

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import purchases.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0012_vendor_credit_limit_vendor_current_balance_and_more'),
        ('branches', '0004_alter_servicebay_unique_together_branch_company_and_more'),
        ('companies', '0004_companysettings_whatsapp_mode'),
        ('jobcards', '0029_workflowchangelog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_number', models.CharField(help_text='Auto-generated purchase number (e.g., PUR-K3-2026-001)', max_length=50, unique=True)),
                ('supplier_invoice_number', models.CharField(blank=True, help_text="Vendor's invoice number", max_length=100, null=True)),
                ('purchase_date', models.DateField(default=django.utils.timezone.now, help_text='Date of purchase')),
                ('due_date', models.DateField(blank=True, help_text='Payment due date', null=True)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Subtotal before tax and discount', max_digits=12)),
                ('discount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total discount amount', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('gst_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total GST amount', max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Final total amount', max_digits=12)),
                ('payment_mode', models.CharField(choices=[('cash', 'Cash'), ('bank_transfer', 'Bank Transfer'), ('upi', 'UPI'), ('cheque', 'Cheque'), ('credit', 'Credit')], default='cash', max_length=20)),
                ('payment_status', models.CharField(choices=[('unpaid', 'Unpaid'), ('partial', 'Partially Paid'), ('paid', 'Paid')], default='unpaid', max_length=20)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total amount paid so far', max_digits=12)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_approval', 'Pending Approval'), ('approved', 'Approved'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Additional notes or comments', null=True)),
                ('invoice_file', models.FileField(blank=True, help_text='Upload supplier invoice (PDF/Image - Max 5MB)', null=True, upload_to='purchases/invoices/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png']), purchases.models.validate_file_size])),
                ('approved_at', models.DateTimeField(blank=True, help_text='When the purchase was approved', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, help_text='User who approved this purchase', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_purchases', to=settings.AUTH_USER_MODEL)),
                ('branch', models.ForeignKey(blank=True, help_text='Branch where purchase was made', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchases', to='branches.branch')),
                ('company', models.ForeignKey(help_text='Company this purchase belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='companies.company')),
                ('created_by', models.ForeignKey(help_text='User who created this purchase', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_purchases', to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(help_text='Supplier/Vendor', on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='accounting.vendor')),
            ],
            options={
                'verbose_name': 'Purchase',
                'verbose_name_plural': 'Purchases',
                'db_table': 'purchases',
                'ordering': ['-purchase_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, help_text='Quantity purchased', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Price per unit', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('discount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Discount on this item', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('gst_rate', models.DecimalField(decimal_places=2, default=Decimal('18.00'), help_text='GST percentage', max_digits=5)),
                ('cgst_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='CGST amount (for intra-state)', max_digits=10)),
                ('sgst_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='SGST amount (for intra-state)', max_digits=10)),
                ('igst_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='IGST amount (for inter-state)', max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total amount for this item', max_digits=12)),
                ('batch_number', models.CharField(blank=True, help_text='Batch/Lot number', max_length=100, null=True)),
                ('expiry_date', models.DateField(blank=True, help_text='Expiry date (if applicable)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('part', models.ForeignKey(help_text='Part/inventory item being purchased', on_delete=django.db.models.deletion.PROTECT, related_name='purchase_items', to='jobcards.part')),
                ('purchase', models.ForeignKey(help_text='Purchase this item belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='purchases.purchase')),
            ],
            options={
                'verbose_name': 'Purchase Item',
                'verbose_name_plural': 'Purchase Items',
                'db_table': 'purchase_items',
                'ordering': ['purchase', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PurchasePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField(default=django.utils.timezone.now, help_text='Date of payment')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Payment amount', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('payment_mode', models.CharField(choices=[('cash', 'Cash'), ('bank_transfer', 'Bank Transfer'), ('upi', 'UPI'), ('cheque', 'Cheque'), ('credit', 'Credit')], default='cash', max_length=20)),
                ('reference_number', models.CharField(blank=True, help_text='Transaction/Cheque reference number', max_length=100, null=True)),
                ('notes', models.TextField(blank=True, help_text='Payment notes', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(help_text='Company this payment belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='purchase_payments', to='companies.company')),
                ('purchase', models.ForeignKey(help_text='Purchase this payment is for', on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='purchases.purchase')),
                ('recorded_by', models.ForeignKey(help_text='User who recorded this payment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_purchase_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Purchase Payment',
                'verbose_name_plural': 'Purchase Payments',
                'db_table': 'purchase_payments',
                'ordering': ['-payment_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_number', models.CharField(help_text='Auto-generated return number (e.g., PRET-K3-2026-001)', max_length=50, unique=True)),
                ('return_date', models.DateField(default=django.utils.timezone.now, help_text='Date of return')),
                ('reason', models.TextField(help_text='Reason for return')),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total return amount', max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Additional notes', null=True)),
                ('approved_at', models.DateTimeField(blank=True, help_text='When the return was approved', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, help_text='User who approved this return', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_purchase_returns', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(help_text='Company this return belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='purchase_returns', to='companies.company')),
                ('created_by', models.ForeignKey(help_text='User who created this return', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_purchase_returns', to=settings.AUTH_USER_MODEL)),
                ('purchase', models.ForeignKey(help_text='Original purchase', on_delete=django.db.models.deletion.PROTECT, related_name='returns', to='purchases.purchase')),
            ],
            options={
                'verbose_name': 'Purchase Return',
                'verbose_name_plural': 'Purchase Returns',
                'db_table': 'purchase_returns',
                'ordering': ['-return_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseReturnItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_returned', models.DecimalField(decimal_places=2, help_text='Quantity being returned', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Return amount for this item', max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('purchase_item', models.ForeignKey(help_text='Original purchase item being returned', on_delete=django.db.models.deletion.PROTECT, related_name='return_items', to='purchases.purchaseitem')),
                ('purchase_return', models.ForeignKey(help_text='Purchase return this item belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='purchases.purchasereturn')),
            ],
            options={
                'verbose_name': 'Purchase Return Item',
                'verbose_name_plural': 'Purchase Return Items',
                'db_table': 'purchase_return_items',
                'ordering': ['purchase_return', 'id'],
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('purchase', 'Purchase'), ('purchase_return', 'Purchase Return'), ('job_card_usage', 'Job Card Usage'), ('adjustment', 'Stock Adjustment'), ('transfer', 'Branch Transfer')], help_text='Type of stock movement', max_length=20)),
                ('quantity', models.DecimalField(decimal_places=2, help_text='Quantity moved (positive for increase, negative for decrease)', max_digits=10)),
                ('reference_type', models.CharField(help_text='Type of reference document (purchase, purchase_return, job_card, etc.)', max_length=50)),
                ('reference_id', models.IntegerField(help_text='ID of reference document')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, help_text='Date and time of movement')),
                ('notes', models.TextField(blank=True, help_text='Additional notes', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(blank=True, help_text='Branch where movement occurred', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to='branches.branch')),
                ('company', models.ForeignKey(help_text='Company this movement belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='companies.company')),
                ('created_by', models.ForeignKey(help_text='User who created this movement', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_stock_movements', to=settings.AUTH_USER_MODEL)),
                ('part', models.ForeignKey(help_text='Part/inventory item', on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='jobcards.part')),
            ],
            options={
                'verbose_name': 'Stock Movement',
                'verbose_name_plural': 'Stock Movements',
                'db_table': 'stock_movements',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SupplierLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_date', models.DateTimeField(default=django.utils.timezone.now, help_text='Date and time of transaction')),
                ('transaction_type', models.CharField(choices=[('purchase', 'Purchase'), ('payment', 'Payment'), ('return', 'Purchase Return'), ('adjustment', 'Adjustment'), ('opening_balance', 'Opening Balance')], help_text='Type of transaction', max_length=20)),
                ('debit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Debit amount (increases supplier balance)', max_digits=12)),
                ('credit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Credit amount (decreases supplier balance)', max_digits=12)),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Running balance after this transaction', max_digits=12)),
                ('description', models.TextField(help_text='Transaction description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(help_text='Company this ledger entry belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='supplier_ledger_entries', to='companies.company')),
                ('payment', models.ForeignKey(blank=True, help_text='Related payment (if applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entries', to='purchases.purchasepayment')),
                ('purchase', models.ForeignKey(blank=True, help_text='Related purchase (if applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entries', to='purchases.purchase')),
                ('return_entry', models.ForeignKey(blank=True, help_text='Related return (if applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entries', to='purchases.purchasereturn')),
                ('supplier', models.ForeignKey(help_text='Supplier this entry is for', on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entries', to='accounting.vendor')),
            ],
            options={
                'verbose_name': 'Supplier Ledger Entry',
                'verbose_name_plural': 'Supplier Ledger Entries',
                'db_table': 'supplier_ledger',
                'ordering': ['supplier', '-transaction_date'],
            },
        ),
        migrations.AddIndex(
            model_name='purchase',
            index=models.Index(fields=['company', 'purchase_date'], name='purchases_company_e78da3_idx'),
        ),
        migrations.AddIndex(
            model_name='purchase',
            index=models.Index(fields=['supplier', 'status'], name='purchases_supplie_51e0dc_idx'),
        ),
        migrations.AddIndex(
            model_name='purchase',
            index=models.Index(fields=['purchase_number'], name='purchases_purchas_12d806_idx'),
        ),
        migrations.AddIndex(
            model_name='purchase',
            index=models.Index(fields=['status', 'payment_status'], name='purchases_status_478f91_idx'),
        ),
        migrations.AddIndex(
            model_name='purchasepayment',
            index=models.Index(fields=['company', 'payment_date'], name='purchase_pa_company_fa8cb8_idx'),
        ),
        migrations.AddIndex(
            model_name='purchasepayment',
            index=models.Index(fields=['purchase', 'payment_date'], name='purchase_pa_purchas_ab1872_idx'),
        ),
        migrations.AddIndex(
            model_name='purchasereturn',
            index=models.Index(fields=['company', 'return_date'], name='purchase_re_company_7e0235_idx'),
        ),
        migrations.AddIndex(
            model_name='purchasereturn',
            index=models.Index(fields=['purchase', 'status'], name='purchase_re_purchas_54714f_idx'),
        ),
        migrations.AddIndex(
            model_name='purchasereturn',
            index=models.Index(fields=['return_number'], name='purchase_re_return__ae7472_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['part', 'date'], name='stock_movem_part_id_f55364_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['branch', 'date'], name='stock_movem_branch__f22d3a_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['movement_type', 'date'], name='stock_movem_movemen_33c9bc_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['reference_type', 'reference_id'], name='stock_movem_referen_a0d8b9_idx'),
        ),
        migrations.AddIndex(
            model_name='supplierledger',
            index=models.Index(fields=['supplier', 'transaction_date'], name='supplier_le_supplie_739357_idx'),
        ),
        migrations.AddIndex(
            model_name='supplierledger',
            index=models.Index(fields=['company', 'transaction_date'], name='supplier_le_company_f1ab7d_idx'),
        ),
        migrations.AddIndex(
            model_name='supplierledger',
            index=models.Index(fields=['transaction_type'], name='supplier_le_transac_789b30_idx'),
        ),
    ]
