# Generated by Django 5.0.1 on 2025-11-17 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0001_initial'),
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='Specific branch (only if is_global=False)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='branches.branch'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_global',
            field=models.BooleanField(default=True, help_text='If True, shared across all branches'),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.IntegerField(default=0, help_text='Global stock count (for global products)'),
        ),
    ]
