# Generated by Django 5.0.1 on 2025-12-12 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_add_branch_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicepackage',
            options={'ordering': ['category', 'name'], 'verbose_name': 'Service Package', 'verbose_name_plural': 'Service Packages'},
        ),
        migrations.AddField(
            model_name='addon',
            name='gst_applicable',
            field=models.BooleanField(default=True, help_text='Whether GST is applicable on this add-on'),
        ),
        migrations.AddField(
            model_name='addon',
            name='gst_rate',
            field=models.DecimalField(decimal_places=2, default=18.0, help_text='GST percentage (e.g., 18.00 for 18%)', max_digits=5),
        ),
        migrations.AddField(
            model_name='servicepackage',
            name='category',
            field=models.CharField(choices=[('wash', 'Car Wash'), ('interior', 'Interior Cleaning'), ('exterior', 'Exterior Beautification'), ('coating', 'Ceramic Coating'), ('makeover', 'Car Makeover'), ('mechanical', 'Mechanical Services'), ('ac_service', 'AC Service'), ('polish', 'Body Polish'), ('other', 'Other Services')], default='other', help_text='Service category for grouping', max_length=50),
        ),
        migrations.AddField(
            model_name='servicepackage',
            name='duration_max',
            field=models.IntegerField(blank=True, help_text='Maximum duration in minutes (for range like 40-50 mins)', null=True),
        ),
        migrations.AddField(
            model_name='servicepackage',
            name='gst_applicable',
            field=models.BooleanField(default=True, help_text='Whether GST is applicable on this service'),
        ),
        migrations.AddField(
            model_name='servicepackage',
            name='gst_rate',
            field=models.DecimalField(decimal_places=2, default=18.0, help_text='GST percentage (e.g., 18.00 for 18%)', max_digits=5),
        ),
        migrations.AddField(
            model_name='servicepackage',
            name='hatchback_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price for Hatchback vehicles', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='servicepackage',
            name='is_variable_pricing',
            field=models.BooleanField(default=False, help_text='If True, use vehicle-type specific pricing instead of base price'),
        ),
        migrations.AddField(
            model_name='servicepackage',
            name='sedan_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price for Sedan vehicles', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='servicepackage',
            name='suv_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price for SUV vehicles', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='servicepackage',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Base price or single price for all vehicle types', max_digits=10),
        ),
    ]
