# Generated by Django 5.0.1 on 2025-12-12 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_alter_servicepackage_options_addon_gst_applicable_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicepackage',
            name='is_variable_pricing',
        ),
        migrations.AlterField(
            model_name='servicepackage',
            name='hatchback_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Price for Hatchback vehicles', max_digits=10),
        ),
        migrations.AlterField(
            model_name='servicepackage',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Legacy base price - use vehicle-type prices instead', max_digits=10),
        ),
        migrations.AlterField(
            model_name='servicepackage',
            name='sedan_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Price for Sedan vehicles', max_digits=10),
        ),
        migrations.AlterField(
            model_name='servicepackage',
            name='suv_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Price for SUV vehicles', max_digits=10),
        ),
    ]
