# Generated by Django 5.0.1 on 2025-12-19 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_simplify_vehicle_pricing'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicepackage',
            name='bike_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Price for Bike vehicles', max_digits=10),
        ),
    ]