# Generated by Django 5.0.1 on 2025-12-19 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_add_bike_price_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicepackage',
            name='compatible_vehicle_types',
            field=models.JSONField(default=list, help_text='List of vehicle types this service is compatible with'),
        ),
        migrations.AlterField(
            model_name='servicepackage',
            name='category',
            field=models.CharField(choices=[('wash', 'Car Wash'), ('interior', 'Interior Cleaning'), ('exterior', 'Exterior Beautification'), ('coating', 'Ceramic Coating'), ('makeover', 'Car Makeover'), ('mechanical', 'Mechanical Services'), ('ac_service', 'AC Service'), ('polish', 'Body Polish'), ('bike_services', 'Bike Services'), ('other', 'Other Services')], default='other', help_text='Service category for grouping', max_length=50),
        ),
    ]
