# Generated by Django 5.0.1 on 2026-01-21 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_servicepackage_compatible_vehicle_types_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='addon',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
