# Generated by Django 5.0.1 on 2026-01-19 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_servicepackage_compatible_vehicle_types_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicepackage',
            name='deduction_enabled',
            field=models.BooleanField(blank=True, help_text='Enable deductions for late completion (service-specific)', null=True),
        ),
        migrations.AddField(
            model_name='servicepackage',
            name='deduction_per_minute',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Deduction amount per minute late (service-specific)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='servicepackage',
            name='deduction_threshold_minutes',
            field=models.IntegerField(blank=True, help_text='Minutes late before deduction applies (service-specific)', null=True),
        ),
        migrations.AddField(
            model_name='servicepackage',
            name='has_custom_rewards',
            field=models.BooleanField(default=False, help_text='Enable custom reward settings for this service (overrides global settings)'),
        ),
        migrations.AddField(
            model_name='servicepackage',
            name='max_deduction_per_job',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Maximum deduction per job (service-specific)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='servicepackage',
            name='tier_1_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Reward amount for tier 1 (service-specific)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='servicepackage',
            name='tier_1_minutes',
            field=models.IntegerField(blank=True, help_text='Minutes early for tier 1 reward (service-specific)', null=True),
        ),
        migrations.AddField(
            model_name='servicepackage',
            name='tier_2_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Reward amount for tier 2 (service-specific)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='servicepackage',
            name='tier_2_minutes',
            field=models.IntegerField(blank=True, help_text='Minutes early for tier 2 reward (service-specific)', null=True),
        ),
        migrations.AddField(
            model_name='servicepackage',
            name='tier_3_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Reward amount for tier 3 (service-specific)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='servicepackage',
            name='tier_3_minutes',
            field=models.IntegerField(blank=True, help_text='Minutes early for tier 3 reward (service-specific)', null=True),
        ),
    ]
