# Generated by Django 5.0.1 on 2026-01-22 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_addon_description'),
        ('services', '0007_service_package_rewards'),
    ]

    operations = [
    ]
