# Generated by Django 5.0.1 on 2026-02-06 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        ('services', '0008_merge_20260122_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='addon',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_addons', to='companies.company'),
        ),
        migrations.AddField(
            model_name='servicepackage',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_packages', to='companies.company'),
        ),
        migrations.AlterUniqueTogether(
            name='servicepackage',
            unique_together={('company', 'name')},
        ),
    ]
