# Generated by Django 5.0.1 on 2026-02-11 18:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_add_domain_model'),
        ('jobcards', '0029_workflowchangelog'),
        ('services', '0009_addon_company_servicepackage_company_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicePackagePart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, help_text='Quantity of this part used per service (e.g., 0.05 for 50ml of 1L bottle)', max_digits=10)),
                ('hatchback_quantity', models.DecimalField(blank=True, decimal_places=2, help_text='Override quantity for hatchback (if different from default)', max_digits=10, null=True)),
                ('sedan_quantity', models.DecimalField(blank=True, decimal_places=2, help_text='Override quantity for sedan (if different from default)', max_digits=10, null=True)),
                ('suv_quantity', models.DecimalField(blank=True, decimal_places=2, help_text='Override quantity for SUV (if different from default)', max_digits=10, null=True)),
                ('bike_quantity', models.DecimalField(blank=True, decimal_places=2, help_text='Override quantity for bike (if different from default)', max_digits=10, null=True)),
                ('is_optional', models.BooleanField(default=False, help_text="If True, this part is optional and won't block service if out of stock")),
                ('is_active', models.BooleanField(default=True, help_text="If False, this part won't be auto-deducted")),
                ('notes', models.TextField(blank=True, help_text='Additional notes about this part usage', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_package_parts', to='companies.company')),
                ('package', models.ForeignKey(help_text='Service package that requires this part', on_delete=django.db.models.deletion.CASCADE, related_name='required_parts', to='services.servicepackage')),
                ('part', models.ForeignKey(help_text='Part required for this service', on_delete=django.db.models.deletion.CASCADE, related_name='used_in_services', to='jobcards.part')),
            ],
            options={
                'verbose_name': 'Service Package Part',
                'verbose_name_plural': 'Service Package Parts',
                'db_table': 'service_package_parts',
                'ordering': ['package', 'part'],
                'indexes': [models.Index(fields=['package'], name='service_pac_package_ddbba3_idx'), models.Index(fields=['part'], name='service_pac_part_id_ec0419_idx'), models.Index(fields=['is_active'], name='service_pac_is_acti_5794eb_idx')],
                'unique_together': {('package', 'part')},
            },
        ),
    ]
