# Generated by Django 5.0.1 on 2026-02-19 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_companysettings_whatsapp_mode'),
        ('jobcards', '0031_add_is_service_default_to_parts_used'),
        ('services', '0010_add_service_package_part_model'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='servicepackagepart',
            unique_together={('package', 'part', 'company')},
        ),
    ]
