# Generated by Django 5.0.1 on 2025-12-19 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_vehiclecolor_vehiclebrand_vehiclemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclemodel',
            name='vehicle_type',
            field=models.CharField(choices=[('hatchback', 'Hatchback'), ('sedan', 'Sedan'), ('suv', 'SUV'), ('bike', 'Bike')], default='sedan', max_length=20),
        ),
    ]
