# Generated by Django 5.0.1 on 2025-12-19 09:41

from django.db import migrations


def update_vehicle_model_types(apps, schema_editor):
    VehicleModel = apps.get_model('customers', 'VehicleModel')
    
    # Define keywords for categorization
    hatchback_keywords = ['alto', 'kwid', 'tiago', 'tigor', 's-presso', 'celerio', 'grand i10', 'santro']
    suv_keywords = ['ertiga', 'brezza', 's-cross', 'fronx', 'grand vitara', 'jimny', 'xuv', 'thar', 'scorpio', 'harrier', 'safari', 'hexa', 'creta', 'venue', 'tucson', 'kona', 'ioniq', 'compass', 'meridian', 'wrangler', 'kushaq', 'slavia', 'kodiaq', 'superb', 'taigun', 'virtus', 'tiguan', 'hector', 'gloster']
    
    # Update all car models with proper vehicle types
    for model in VehicleModel.objects.all():
        if model.brand.vehicle_type == 'bike':
            model.vehicle_type = 'bike'
            model.save()
        else:
            # Determine vehicle type based on model name
            vehicle_type = 'sedan'  # default for cars
            
            # Hatchbacks
            if any(keyword in model.brand.name.lower() for keyword in ['maruti', 'renault', 'nissan']) or any(keyword in model.name.lower() for keyword in hatchback_keywords):
                vehicle_type = 'hatchback'
            
            # SUVs
            if any(keyword in model.name.lower() for keyword in suv_keywords):
                vehicle_type = 'suv'
            
            model.vehicle_type = vehicle_type
            model.save()


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_vehiclemodel_vehicle_type'),
    ]

    operations = [
        migrations.RunPython(update_vehicle_model_types),
    ]
