# Generated by Django 5.0.1 on 2025-12-20 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0006_update_vehicle_model_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='vehicle_type',
            field=models.CharField(choices=[('hatchback', 'Hatchback'), ('sedan', 'Sedan'), ('suv', 'SUV'), ('bike', 'Bike')], default='sedan', help_text='Vehicle type for determining service pricing', max_length=20),
        ),
    ]
