# Generated by Django 5.0.1 on 2026-01-31 10:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0007_add_vehicle_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('color', models.CharField(default='#3B82F6', help_text='Hex color code', max_length=7)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Customer Tag',
                'verbose_name_plural': 'Customer Tags',
                'db_table': 'customer_tags',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='vehicle',
            name='odometer_reading',
            field=models.IntegerField(blank=True, help_text='Current odometer reading in KM', null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='service_interval_days',
            field=models.IntegerField(default=90, help_text='Service interval in days'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='service_interval_km',
            field=models.IntegerField(default=5000, help_text='Service interval in kilometers'),
        ),
        migrations.CreateModel(
            name='CustomerLifecycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_stage', models.CharField(choices=[('lead', 'Lead'), ('prospect', 'Prospect'), ('active', 'Active'), ('at_risk', 'At Risk'), ('churned', 'Churned'), ('won_back', 'Won Back')], default='active', max_length=20)),
                ('previous_stage', models.CharField(blank=True, choices=[('lead', 'Lead'), ('prospect', 'Prospect'), ('active', 'Active'), ('at_risk', 'At Risk'), ('churned', 'Churned'), ('won_back', 'Won Back')], max_length=20)),
                ('stage_changed_at', models.DateTimeField(auto_now=True)),
                ('acquisition_source', models.CharField(blank=True, help_text='Walk-in, Referral, Online, Marketing', max_length=50)),
                ('acquisition_date', models.DateField(blank=True, null=True)),
                ('last_interaction_date', models.DateField(blank=True, null=True)),
                ('total_lifetime_value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('customer_score', models.IntegerField(default=0, help_text='Calculated customer score based on activity')),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lifecycle', to='customers.customer')),
            ],
            options={
                'verbose_name': 'Customer Lifecycle',
                'verbose_name_plural': 'Customer Lifecycles',
                'db_table': 'customer_lifecycle',
            },
        ),
        migrations.CreateModel(
            name='CustomerNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('general', 'General'), ('preference', 'Preference'), ('complaint', 'Complaint'), ('feedback', 'Feedback'), ('follow_up', 'Follow Up'), ('special_request', 'Special Request')], default='general', max_length=20)),
                ('note', models.TextField()),
                ('is_important', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_notes_created', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='customers.customer')),
            ],
            options={
                'verbose_name': 'Customer Note',
                'verbose_name_plural': 'Customer Notes',
                'db_table': 'customer_notes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReminderHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_type', models.CharField(max_length=50)),
                ('sent_via', models.CharField(help_text='email, sms, whatsapp', max_length=20)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('opened', models.BooleanField(default=False)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('clicked', models.BooleanField(default=False)),
                ('clicked_at', models.DateTimeField(blank=True, null=True)),
                ('content', models.TextField(blank=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminder_history', to='customers.customer')),
            ],
            options={
                'verbose_name': 'Reminder History',
                'verbose_name_plural': 'Reminder Histories',
                'db_table': 'reminder_history',
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomerActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('booking_created', 'Booking Created'), ('booking_completed', 'Booking Completed'), ('payment_made', 'Payment Made'), ('call_made', 'Call Made'), ('call_received', 'Call Received'), ('email_sent', 'Email Sent'), ('sms_sent', 'SMS Sent'), ('whatsapp_sent', 'WhatsApp Sent'), ('note_added', 'Note Added'), ('complaint_logged', 'Complaint Logged'), ('feedback_given', 'Feedback Given'), ('membership_purchased', 'Membership Purchased'), ('referral_made', 'Referral Made')], max_length=30)),
                ('description', models.TextField()),
                ('reference_type', models.CharField(blank=True, help_text='Type of related object', max_length=50)),
                ('reference_id', models.IntegerField(blank=True, help_text='ID of related object', null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_activities_created', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='customers.customer')),
            ],
            options={
                'verbose_name': 'Customer Activity',
                'verbose_name_plural': 'Customer Activities',
                'db_table': 'customer_activities',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['customer', '-timestamp'], name='customer_ac_custome_3274b4_idx'), models.Index(fields=['activity_type', '-timestamp'], name='customer_ac_activit_62abbb_idx')],
            },
        ),
        migrations.CreateModel(
            name='CustomerPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100)),
                ('value', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to='customers.customer')),
            ],
            options={
                'verbose_name': 'Customer Preference',
                'verbose_name_plural': 'Customer Preferences',
                'db_table': 'customer_preferences',
                'unique_together': {('customer', 'key')},
            },
        ),
        migrations.CreateModel(
            name='CustomerSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('segment_type', models.CharField(choices=[('vip', 'VIP'), ('regular', 'Regular'), ('inactive', 'Inactive'), ('new', 'New'), ('at_risk', 'At Risk'), ('corporate', 'Corporate')], max_length=20)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_segments_assigned', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='customers.customer')),
            ],
            options={
                'verbose_name': 'Customer Segment',
                'verbose_name_plural': 'Customer Segments',
                'db_table': 'customer_segments',
                'unique_together': {('customer', 'segment_type')},
            },
        ),
        migrations.CreateModel(
            name='ServiceReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_date', models.DateField()),
                ('reminder_type', models.CharField(default='regular_service', max_length=50)),
                ('message', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('sent_via', models.CharField(blank=True, help_text='email, sms, whatsapp', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_reminders', to='customers.customer')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_reminders', to='customers.vehicle')),
            ],
            options={
                'verbose_name': 'Service Reminder',
                'verbose_name_plural': 'Service Reminders',
                'db_table': 'service_reminders',
                'ordering': ['due_date'],
                'indexes': [models.Index(fields=['customer', 'due_date'], name='service_rem_custome_e51743_idx'), models.Index(fields=['status', 'due_date'], name='service_rem_status_4448c8_idx')],
            },
        ),
    ]
