# Generated by Django 5.0.1 on 2026-02-03 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0009_remove_registration_unique_constraint'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferralCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Unique referral code', max_length=50, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('times_used', models.IntegerField(default=0, help_text='Number of times this code has been used')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='referral_code_obj', to='customers.customer')),
            ],
            options={
                'verbose_name': 'Referral Code',
                'verbose_name_plural': 'Referral Codes',
                'db_table': 'referral_codes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referral_code', models.CharField(help_text='The referral code used', max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('rewarded', 'Rewarded')], default='pending', max_length=20)),
                ('referrer_points_awarded', models.DecimalField(decimal_places=2, default=0, help_text='Points/amount credited to referrer', max_digits=10)),
                ('referee_points_awarded', models.DecimalField(decimal_places=2, default=0, help_text='Points/amount credited to referee', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='When referee completed their first job', null=True)),
                ('rewarded_at', models.DateTimeField(blank=True, help_text='When rewards were credited', null=True)),
                ('referee', models.ForeignKey(help_text='Customer who was referred', on_delete=django.db.models.deletion.CASCADE, related_name='referrals_received', to='customers.customer')),
                ('referrer', models.ForeignKey(help_text='Customer who made the referral', on_delete=django.db.models.deletion.CASCADE, related_name='referrals_made', to='customers.customer')),
            ],
            options={
                'verbose_name': 'Referral',
                'verbose_name_plural': 'Referrals',
                'db_table': 'referrals',
                'ordering': ['-created_at'],
                'unique_together': {('referrer', 'referee')},
            },
        ),
    ]
