# Generated by Django 5.0.1 on 2026-02-04 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0010_referralcode_referral'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='referralcode',
            index=models.Index(fields=['code'], name='idx_referral_code'),
        ),
        migrations.AddIndex(
            model_name='referralcode',
            index=models.Index(fields=['is_active'], name='idx_referral_active'),
        ),
    ]
