# Generated by Django 5.0.1 on 2026-02-06 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        ('customers', '0011_referralcode_idx_referral_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='companies.company'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='companies.company'),
        ),
        migrations.AlterUniqueTogether(
            name='vehicle',
            unique_together={('company', 'registration_number')},
        ),
    ]
