# Generated by Django 5.0.1 on 2026-02-06 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        ('feedback', '0002_add_feedback_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='companies.company'),
        ),
    ]
