# Generated by Django 5.0.1 on 2025-12-21 12:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_employeesalarystructure_payroll_pettycash_and_more'),
        ('branches', '0002_branch_google_review_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InterBranchTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_type', models.CharField(choices=[('fund', 'Fund Transfer'), ('expense_reallocation', 'Expense Reallocation')], default='fund', max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField()),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_transfers', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_transfers', to=settings.AUTH_USER_MODEL)),
                ('expense', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reallocations', to='accounting.expense')),
                ('from_branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_transfers', to='branches.branch')),
                ('to_branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_transfers', to='branches.branch')),
            ],
            options={
                'db_table': 'inter_branch_transfers',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BranchBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_type', models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly')], max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('total_budget', models.DecimalField(decimal_places=2, max_digits=12)),
                ('inventory_budget', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('salary_budget', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('utilities_budget', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('rent_budget', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('maintenance_budget', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('marketing_budget', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('other_budget', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='branches.branch')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'branch_budgets',
                'ordering': ['-start_date'],
                'unique_together': {('branch', 'start_date', 'end_date')},
            },
        ),
    ]
