# Generated by Django 5.0.1 on 2026-01-24 17:35

import accounting.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_leavetype_payroll_leave_deduction_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='receipt',
            field=models.FileField(blank=True, help_text='Upload receipt (PDF/Image - Max 5MB)', null=True, upload_to='expenses/receipts/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png']), accounting.models.validate_file_size]),
        ),
    ]
