# Generated by Django 5.0.1 on 2026-01-31 07:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0005_alter_expense_receipt'),
        ('branches', '0002_branch_google_review_url'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalWorkflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Workflow name (e.g., 'High Value Expense Approval')", max_length=200)),
                ('model_type', models.CharField(choices=[('expense', 'Expense'), ('transfer', 'Inter-Branch Transfer'), ('budget', 'Branch Budget'), ('payroll', 'Payroll')], max_length=50)),
                ('threshold_amount', models.DecimalField(decimal_places=2, help_text='Minimum amount that triggers this workflow', max_digits=12)),
                ('levels', models.IntegerField(default=1, help_text='Number of approval levels required')),
                ('approver_roles', models.JSONField(blank=True, default=list, help_text="Roles that can approve (e.g., ['branch_admin', 'accountant'])")),
                ('auto_approve_below', models.DecimalField(blank=True, decimal_places=2, help_text='Auto-approve if amount is below this value', max_digits=12, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approvers', models.ManyToManyField(blank=True, help_text='Specific users who can approve (leave empty for role-based)', related_name='approval_workflows', to=settings.AUTH_USER_MODEL)),
                ('branch', models.ForeignKey(blank=True, help_text='Leave blank for global workflow', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approval_workflows', to='branches.branch')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_workflows', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'approval_workflows',
                'ordering': ['model_type', '-threshold_amount'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('description', models.TextField()),
                ('current_level', models.IntegerField(default=1)),
                ('required_levels', models.IntegerField(default=1)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_requests_made', to=settings.AUTH_USER_MODEL)),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='accounting.approvalworkflow')),
            ],
            options={
                'db_table': 'approval_requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('approved', 'Approved'), ('rejected', 'Rejected')], max_length=20)),
                ('level', models.IntegerField(help_text='Approval level at which action was taken')),
                ('comments', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_actions', to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='accounting.approvalrequest')),
            ],
            options={
                'db_table': 'approval_actions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['request', 'level'], name='approval_ac_request_8bcc8b_idx'), models.Index(fields=['approver', 'created_at'], name='approval_ac_approve_f95c7e_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='approvalworkflow',
            index=models.Index(fields=['model_type', 'is_active'], name='approval_wo_model_t_f0d7ff_idx'),
        ),
        migrations.AddIndex(
            model_name='approvalworkflow',
            index=models.Index(fields=['branch', 'is_active'], name='approval_wo_branch__5348cf_idx'),
        ),
        migrations.AddIndex(
            model_name='approvalrequest',
            index=models.Index(fields=['status', 'created_at'], name='approval_re_status_208432_idx'),
        ),
        migrations.AddIndex(
            model_name='approvalrequest',
            index=models.Index(fields=['requested_by', 'status'], name='approval_re_request_5440d5_idx'),
        ),
        migrations.AddIndex(
            model_name='approvalrequest',
            index=models.Index(fields=['content_type', 'object_id'], name='approval_re_content_4a83b3_idx'),
        ),
    ]
