# Generated by Django 5.0.1 on 2026-02-01 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0006_approvalworkflow_approvalrequest_approvalaction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='partial_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Amount paid if payment_status is 'partial'", max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('online', 'Online')], default='cash', help_text='Payment method', max_length=20),
        ),
    ]
