# Generated by Django 5.0.1 on 2026-02-02 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0007_expense_partial_amount_expense_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('cash', 'Cash'), ('card', 'Card'), ('upi', 'UPI'), ('cheque', 'Cheque'), ('bank_transfer', 'Bank Transfer'), ('stripe', 'Stripe'), ('wallet', 'Wallet'), ('gift_card', 'Gift Card'), ('other', 'Other')], help_text='Payment method used for this transaction', max_length=20, null=True),
        ),
    ]
