# Generated by Django 5.0.1 on 2026-02-02 19:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0008_add_payment_method_to_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('cash', 'Cash'), ('card', 'Card'), ('upi', 'UPI'), ('cheque', 'Cheque'), ('bank_transfer', 'Bank Transfer'), ('stripe', 'Stripe'), ('wallet', 'Wallet'), ('gift_card', 'Gift Card'), ('online', 'Online'), ('other', 'Other')], help_text='Payment method used for this transaction', max_length=20, null=True),
        ),
    ]
