# Generated by Django 5.0.1 on 2026-02-16 11:28

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0011_expense_company_transaction_company_vendor_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='credit_limit',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Maximum credit limit allowed', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='current_balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Current outstanding balance', max_digits=12),
        ),
        migrations.AddField(
            model_name='vendor',
            name='is_approved',
            field=models.BooleanField(default=True, help_text='Whether this supplier is approved for purchases'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='opening_balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Opening balance (amount owed to supplier)', max_digits=12),
        ),
        migrations.AddField(
            model_name='vendor',
            name='payment_terms_days',
            field=models.IntegerField(default=30, help_text='Payment terms in days (e.g., 30 for Net 30)'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='supplier_rating',
            field=models.IntegerField(default=3, help_text='Supplier rating (1-5 stars)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
