# Generated by Django 5.0.1 on 2026-03-14 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0005_companysettings_wp_api_key_companysettings_wp_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingWhatsAppEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(default='message_received', max_length=50)),
                ('phone_number', models.CharField(max_length=20)),
                ('message_type', models.CharField(default='text', max_length=20)),
                ('message_content', models.TextField(blank=True, null=True)),
                ('message_id', models.CharField(blank=True, max_length=255, null=True)),
                ('raw_payload', models.JSONField(default=dict, help_text='Raw webhook json payload')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processed', 'Processed'), ('ignored', 'Ignored')], default='pending', max_length=20)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_events', to='companies.company')),
            ],
            options={
                'ordering': ['-received_at'],
            },
        ),
    ]
