# Generated by Django 5.0.1 on 2025-11-17 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='branch',
            field=models.CharField(blank=True, help_text='Branch assignment for admin/staff', max_length=100, null=True),
        ),
    ]
