# Generated by Django 5.0.1 on 2025-11-17 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0001_initial'),
        ('users', '0002_user_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='Branch assignment for admin/staff', null=True, on_delete=django.db.models.deletion.SET_NULL, to='branches.branch'),
        ),
    ]
