# Generated by Django 5.0.1 on 2025-12-02 03:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0001_initial'),
        ('users', '0003_alter_user_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='Branch assignment for branch_admin/floor_manager/supervisor', null=True, on_delete=django.db.models.deletion.SET_NULL, to='branches.branch'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('branch_admin', 'Branch Admin'), ('floor_manager', 'Floor Manager'), ('supervisor', 'Supervisor'), ('customer', 'Customer')], default='customer', max_length=20),
        ),
    ]
