# Generated by Django 5.0.1 on 2025-12-02 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_update_role_choices'),
    ]

    operations = [
    ]
