# Generated by Django 5.0.1 on 2025-12-06 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_migrate_role_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('branch_admin', 'Branch Admin'), ('floor_manager', 'Floor Manager'), ('supervisor', 'Supervisor'), ('applicator', 'Applicator'), ('customer', 'Customer')], default='customer', max_length=20),
        ),
    ]
