# Generated by Django 5.0.1 on 2026-02-06 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        ('users', '0008_user_anniversary_user_birthday'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='company',
            field=models.ForeignKey(blank=True, help_text='Company/Organization this user belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='companies.company'),
        ),
    ]
