# Generated by Django 5.0.1 on 2026-01-31 07:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0005_alter_expense_receipt'),
        ('branches', '0002_branch_google_review_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendancePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Policy name', max_length=200)),
                ('standard_working_hours', models.DecimalField(decimal_places=2, default=8, help_text='Standard working hours per day', max_digits=4)),
                ('late_arrival_grace_minutes', models.IntegerField(default=15, help_text='Grace period for late arrival in minutes')),
                ('half_day_hours', models.DecimalField(decimal_places=2, default=4, help_text='Minimum hours for half day', max_digits=4)),
                ('overtime_threshold_hours', models.DecimalField(decimal_places=2, default=8, help_text='Hours after which overtime starts', max_digits=4)),
                ('weekly_off_days', models.JSONField(default=list, help_text='List of weekly off days (0=Monday, 6=Sunday)')),
                ('applies_to_roles', models.JSONField(blank=True, default=list, help_text='List of roles this policy applies to (empty = all)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applies_to_branches', models.ManyToManyField(blank=True, related_name='attendance_policies', to='branches.branch')),
            ],
            options={
                'verbose_name_plural': 'Attendance Policies',
                'db_table': 'attendance_policies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('half_day', 'Half Day'), ('on_leave', 'On Leave'), ('holiday', 'Holiday'), ('week_off', 'Week Off')], default='present', max_length=20)),
                ('check_in_time', models.TimeField(blank=True, null=True)),
                ('check_out_time', models.TimeField(blank=True, null=True)),
                ('total_hours', models.DecimalField(decimal_places=2, default=0, help_text='Total working hours', max_digits=5)),
                ('overtime_hours', models.DecimalField(decimal_places=2, default=0, help_text='Overtime hours worked', max_digits=5)),
                ('notes', models.TextField(blank=True, help_text='Reason for absence, late arrival, etc.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_records', to='branches.branch')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to=settings.AUTH_USER_MODEL)),
                ('leave_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_records', to='accounting.leaverequest')),
                ('marked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marked_attendance', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'attendance_records',
                'ordering': ['-date', 'employee'],
                'indexes': [models.Index(fields=['employee', 'date'], name='attendance__employe_6b3da7_idx'), models.Index(fields=['branch', 'date'], name='attendance__branch__efc627_idx'), models.Index(fields=['status', 'date'], name='attendance__status_756504_idx')],
                'unique_together': {('employee', 'date')},
            },
        ),
        migrations.CreateModel(
            name='MonthlyAttendanceSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField(help_text='Month (1-12)')),
                ('year', models.IntegerField(help_text='Year')),
                ('total_working_days', models.IntegerField(default=0)),
                ('days_present', models.IntegerField(default=0)),
                ('days_absent', models.IntegerField(default=0)),
                ('days_half_day', models.IntegerField(default=0)),
                ('days_on_leave', models.IntegerField(default=0)),
                ('days_holiday', models.IntegerField(default=0)),
                ('days_week_off', models.IntegerField(default=0)),
                ('total_hours_worked', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('total_overtime_hours', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('late_arrivals_count', models.IntegerField(default=0)),
                ('effective_working_days', models.DecimalField(decimal_places=2, default=0, help_text='Present + (Half Day * 0.5) + Leave', max_digits=5)),
                ('is_auto_generated', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_summaries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'monthly_attendance_summaries',
                'ordering': ['-year', '-month', 'employee'],
                'indexes': [models.Index(fields=['month', 'year'], name='monthly_att_month_d110b4_idx'), models.Index(fields=['employee', 'month', 'year'], name='monthly_att_employe_eaf3bd_idx')],
                'unique_together': {('employee', 'month', 'year')},
            },
        ),
    ]
