# Generated by Django 5.0.1 on 2025-11-26 04:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notify', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InAppNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('booking_created', 'Booking Created'), ('booking_confirmed', 'Booking Confirmed'), ('booking_cancelled', 'Booking Cancelled'), ('job_started', 'Job Started'), ('job_in_progress', 'Job In Progress'), ('job_completed', 'Job Completed'), ('payment_success', 'Payment Success'), ('payment_failed', 'Payment Failed'), ('invoice_created', 'Invoice Created'), ('feedback_request', 'Feedback Request')], max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('related_booking_id', models.IntegerField(blank=True, null=True)),
                ('related_jobcard_id', models.IntegerField(blank=True, null=True)),
                ('related_invoice_id', models.IntegerField(blank=True, null=True)),
                ('extra_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_app_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'In-App Notification',
                'verbose_name_plural': 'In-App Notifications',
                'db_table': 'in_app_notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'is_read'], name='in_app_noti_recipie_e6eb25_idx'), models.Index(fields=['created_at'], name='in_app_noti_created_1256a3_idx')],
            },
        ),
    ]
