# Generated by Django 5.0.1 on 2025-11-28 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notify', '0002_inappnotification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inappnotification',
            name='notification_type',
            field=models.CharField(choices=[('booking_created', 'Booking Created'), ('booking_confirmed', 'Booking Confirmed'), ('booking_cancelled', 'Booking Cancelled'), ('technician_assigned', 'Technician Assigned'), ('job_started', 'Job Started'), ('job_in_progress', 'Job In Progress'), ('job_completed', 'Job Completed'), ('payment_success', 'Payment Success'), ('payment_failed', 'Payment Failed'), ('invoice_created', 'Invoice Created'), ('feedback_request', 'Feedback Request')], max_length=50),
        ),
    ]
