# Generated by Django 5.0.1 on 2025-12-02 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notify', '0004_alter_inappnotification_notification_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inappnotification',
            name='notification_type',
            field=models.CharField(choices=[('booking_created', 'Booking Created'), ('booking_confirmed', 'Booking Confirmed'), ('booking_cancelled', 'Booking Cancelled'), ('technician_assigned', 'Technician Assigned'), ('job_created', 'Job Created'), ('job_started', 'Job Started'), ('job_in_progress', 'Job In Progress'), ('job_completed', 'Job Completed'), ('job_warning', 'Job Time Warning'), ('job_overdue', 'Job Overdue'), ('payment_success', 'Payment Success'), ('payment_failed', 'Payment Failed'), ('invoice_created', 'Invoice Created'), ('feedback_request', 'Feedback Request')], max_length=50),
        ),
        migrations.AlterField(
            model_name='notificationtemplate',
            name='notification_type',
            field=models.CharField(choices=[('booking_created', 'Booking Created'), ('booking_confirmed', 'Booking Confirmed'), ('booking_cancelled', 'Booking Cancelled'), ('technician_assigned', 'Technician Assigned'), ('job_created', 'Job Created'), ('job_started', 'Job Started'), ('job_in_progress', 'Job In Progress'), ('job_completed', 'Job Completed'), ('job_warning', 'Job Time Warning'), ('job_overdue', 'Job Overdue'), ('payment_success', 'Payment Success'), ('payment_failed', 'Payment Failed'), ('invoice_created', 'Invoice Created'), ('feedback_request', 'Feedback Request')], max_length=50, unique=True),
        ),
    ]
