# Generated by Django 5.0.1 on 2026-02-06 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        ('notify', '0009_alter_inappnotification_notification_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inappnotification',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='in_app_notifications', to='companies.company'),
        ),
        migrations.AddField(
            model_name='notificationtemplate',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification_templates', to='companies.company'),
        ),
    ]
