# Generated by Django 5.0.1 on 2026-02-12 13:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_companysettings_enable_whatsapp_notifications_and_more'),
        ('notify', '0010_inappnotification_company_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_name', models.CharField(help_text='Template name in WhatsApp (lowercase, underscores only)', max_length=100)),
                ('notification_type', models.CharField(help_text='Maps to NotificationTemplate.notification_type', max_length=50)),
                ('category', models.CharField(choices=[('TRANSACTIONAL', 'Transactional'), ('MARKETING', 'Marketing'), ('AUTHENTICATION', 'Authentication')], default='TRANSACTIONAL', max_length=20)),
                ('language', models.CharField(default='en', help_text="Language code (e.g., 'en', 'hi')", max_length=10)),
                ('header_text', models.CharField(blank=True, help_text='Optional header text', max_length=60)),
                ('body_text', models.TextField(help_text='Body text with {{1}}, {{2}} placeholders')),
                ('footer_text', models.CharField(blank=True, help_text='Optional footer text', max_length=60)),
                ('variable_mapping', models.JSONField(blank=True, default=dict, help_text='Maps {{1}}, {{2}} to context variables')),
                ('button_config', models.JSONField(blank=True, default=list)),
                ('whatsapp_template_id', models.CharField(blank=True, help_text='Template ID from WhatsApp API', max_length=100)),
                ('approval_status', models.CharField(choices=[('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_templates', to='companies.company')),
            ],
            options={
                'verbose_name': 'WhatsApp Template',
                'verbose_name_plural': 'WhatsApp Templates',
                'db_table': 'whatsapp_templates',
                'ordering': ['company', 'template_name'],
                'unique_together': {('company', 'template_name')},
            },
        ),
        migrations.CreateModel(
            name='WhatsAppMessageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_phone', models.CharField(max_length=20)),
                ('template_name', models.CharField(max_length=100)),
                ('message_content', models.TextField(help_text='Rendered message content')),
                ('whatsapp_message_id', models.CharField(blank=True, help_text='Message ID from WhatsApp API', max_length=100)),
                ('status', models.CharField(choices=[('QUEUED', 'Queued'), ('SENT', 'Sent'), ('DELIVERED', 'Delivered'), ('READ', 'Read'), ('FAILED', 'Failed')], default='QUEUED', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('error_code', models.CharField(blank=True, max_length=50)),
                ('related_booking_id', models.IntegerField(blank=True, null=True)),
                ('related_jobcard_id', models.IntegerField(blank=True, null=True)),
                ('related_invoice_id', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_messages', to='companies.company')),
                ('recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_messages', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_messages', to='notify.whatsapptemplate')),
            ],
            options={
                'verbose_name': 'WhatsApp Message Log',
                'verbose_name_plural': 'WhatsApp Message Logs',
                'db_table': 'whatsapp_message_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['company', 'status'], name='whatsapp_me_company_5218de_idx'), models.Index(fields=['whatsapp_message_id'], name='whatsapp_me_whatsap_300313_idx'), models.Index(fields=['created_at'], name='whatsapp_me_created_d6ade4_idx')],
            },
        ),
    ]
