# Generated by Django 5.0.1 on 2026-02-12 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notify', '0011_whatsapptemplate_whatsappmessagelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappmessagelog',
            name='whatsapp_link',
            field=models.URLField(blank=True, help_text='wa.me link for manual sending (manual mode only)', max_length=500),
        ),
        migrations.AlterField(
            model_name='whatsappmessagelog',
            name='status',
            field=models.CharField(choices=[('QUEUED', 'Queued'), ('SENT', 'Sent'), ('DELIVERED', 'Delivered'), ('READ', 'Read'), ('FAILED', 'Failed'), ('PENDING_MANUAL', 'Pending Manual Send'), ('SENT_MANUAL', 'Sent Manually')], default='QUEUED', max_length=20),
        ),
    ]
