# Generated by Django 5.0.1 on 2025-12-21 06:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0008_booking_coupon'),
        ('branches', '0002_branch_google_review_url'),
        ('customers', '0007_add_vehicle_type'),
        ('services', '0006_servicepackage_compatible_vehicle_types_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type', models.CharField(choices=[('hatchback', 'Hatchback'), ('sedan', 'Sedan'), ('suv', 'SUV'), ('bike', 'Bike')], default='sedan', max_length=20)),
                ('preferred_datetime', models.DateTimeField(help_text='Customer preferred date/time')),
                ('alternate_datetime', models.DateTimeField(blank=True, help_text='Customer alternate date/time (optional)', null=True)),
                ('confirmed_datetime', models.DateTimeField(blank=True, help_text='Final confirmed datetime (set by admin)', null=True)),
                ('pickup_required', models.BooleanField(default=False)),
                ('location', models.TextField(blank=True, help_text='Pickup/Service location', null=True)),
                ('notes', models.TextField(blank=True, help_text='Customer notes', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('converted', 'Converted to Booking'), ('expired', 'Expired'), ('cancelled', 'Cancelled by Customer')], default='pending', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('admin_notes', models.TextField(blank=True, help_text='Admin notes/rejection reason', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Appointment expires after this datetime', null=True)),
                ('addons', models.ManyToManyField(blank=True, related_name='appointments', to='services.addon')),
                ('booking', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_appointment', to='bookings.booking')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='branches.branch')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='customers.customer')),
                ('package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='services.servicepackage')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_appointments', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='customers.vehicle')),
            ],
            options={
                'verbose_name': 'Appointment',
                'verbose_name_plural': 'Appointments',
                'db_table': 'appointments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AppointmentSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('max_bookings', models.PositiveIntegerField(default=5, help_text='Maximum appointments for this slot')),
                ('is_available', models.BooleanField(default=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointment_slots', to='branches.branch')),
            ],
            options={
                'db_table': 'appointment_slots',
                'ordering': ['date', 'start_time'],
                'unique_together': {('branch', 'date', 'start_time')},
            },
        ),
    ]
