# Generated by Django 5.0.1 on 2026-02-02 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_invoice_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='discount_percentage',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Discount percentage (if type is percentage)', max_digits=5),
        ),
        migrations.AddField(
            model_name='invoice',
            name='discount_reason',
            field=models.CharField(blank=True, help_text='Reason for discount (audit trail)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='discount_type',
            field=models.CharField(choices=[('none', 'No Discount'), ('percentage', 'Percentage'), ('fixed', 'Fixed Amount'), ('coupon', 'Coupon Code')], default='none', max_length=20),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Final discount amount applied', max_digits=10),
        ),
    ]
