# Generated by Django 5.0.1 on 2026-02-04 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_invoice_discount_percentage_invoice_discount_reason_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='discount_percentage',
        ),
        migrations.AddField(
            model_name='invoice',
            name='additional_discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='invoice',
            name='additional_discount_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='invoice',
            name='additional_discount_type',
            field=models.CharField(choices=[('none', 'No Discount'), ('percentage', 'Percentage'), ('fixed', 'Fixed Amount'), ('coupon', 'Coupon Code')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='invoice',
            name='system_discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Discount carried over from booking', max_digits=10),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total combined discount amount', max_digits=10),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='discount_reason',
            field=models.CharField(blank=True, help_text='Reason for discount', max_length=255, null=True),
        ),
    ]
