# Generated by Django 5.0.1 on 2026-01-31 10:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0007_add_vehicle_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('send_email', 'Send Email'), ('send_sms', 'Send SMS'), ('send_whatsapp', 'Send WhatsApp'), ('create_notification', 'Create Notification'), ('update_status', 'Update Status'), ('assign_task', 'Assign Task')], max_length=50)),
                ('channel', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('whatsapp', 'WhatsApp'), ('notification', 'In-App Notification'), ('system', 'System Action')], max_length=20)),
                ('template_id', models.IntegerField(blank=True, help_text='ID of the message template', null=True)),
                ('template_content', models.TextField(blank=True, help_text='Template content with variables')),
                ('delay_minutes', models.IntegerField(default=0, help_text='Delay after previous action (in minutes)')),
                ('order', models.IntegerField(default=0, help_text='Execution order')),
                ('config', models.JSONField(blank=True, default=dict, help_text='Additional configuration')),
            ],
            options={
                'verbose_name': 'Workflow Action',
                'verbose_name_plural': 'Workflow Actions',
                'ordering': ['workflow', 'order'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_type', models.CharField(blank=True, help_text='Type of object that triggered (booking, invoice, etc)', max_length=50)),
                ('reference_id', models.IntegerField(blank=True, help_text='ID of the object that triggered', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('triggered_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('context_data', models.JSONField(blank=True, default=dict, help_text='Context data for template rendering')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workflow_executions', to='customers.customer')),
            ],
            options={
                'verbose_name': 'Workflow Execution',
                'verbose_name_plural': 'Workflow Executions',
                'ordering': ['-triggered_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='pending', max_length=20)),
                ('message', models.TextField(blank=True)),
                ('error_details', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('execution_time_ms', models.IntegerField(blank=True, help_text='Execution time in milliseconds', null=True)),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='automation.workflowaction')),
                ('execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='automation.workflowexecution')),
            ],
            options={
                'verbose_name': 'Workflow Log',
                'verbose_name_plural': 'Workflow Logs',
                'ordering': ['execution', 'action__order', 'timestamp'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('trigger_type', models.CharField(choices=[('booking_created', 'Booking Created'), ('booking_confirmed', 'Booking Confirmed'), ('service_completed', 'Service Completed'), ('payment_received', 'Payment Received'), ('invoice_overdue', 'Invoice Overdue'), ('customer_birthday', 'Customer Birthday'), ('customer_anniversary', 'Customer Anniversary'), ('membership_expiry', 'Membership Expiry'), ('inactive_customer', 'Inactive Customer'), ('appointment_reminder', 'Appointment Reminder')], max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='automation_workflows_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Workflow Template',
                'verbose_name_plural': 'Workflow Templates',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='workflowexecution',
            name='workflow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='automation.workflowtemplate'),
        ),
        migrations.CreateModel(
            name='WorkflowAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_executions', models.IntegerField(default=0)),
                ('successful_executions', models.IntegerField(default=0)),
                ('failed_executions', models.IntegerField(default=0)),
                ('average_execution_time_ms', models.IntegerField(default=0)),
                ('total_customers_reached', models.IntegerField(default=0)),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='automation.workflowtemplate')),
            ],
            options={
                'verbose_name': 'Workflow Analytics',
                'verbose_name_plural': 'Workflow Analytics',
                'ordering': ['-date'],
            },
        ),
        migrations.AddField(
            model_name='workflowaction',
            name='workflow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='automation.workflowtemplate'),
        ),
        migrations.CreateModel(
            name='WorkflowTrigger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=50)),
                ('conditions', models.JSONField(blank=True, default=dict, help_text='JSON conditions for triggering')),
                ('delay_minutes', models.IntegerField(default=0, help_text='Delay before executing workflow (in minutes)')),
                ('workflow', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trigger', to='automation.workflowtemplate')),
            ],
        ),
        migrations.AddIndex(
            model_name='workflowexecution',
            index=models.Index(fields=['workflow', 'status'], name='automation__workflo_2bbb85_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowexecution',
            index=models.Index(fields=['customer', 'triggered_at'], name='automation__custome_a83409_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowanalytics',
            index=models.Index(fields=['workflow', 'date'], name='automation__workflo_926e1c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='workflowanalytics',
            unique_together={('workflow', 'date')},
        ),
    ]
