# Generated by Django 5.0.1 on 2025-11-16 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PickupDropRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_time', models.DateTimeField(blank=True, null=True)),
                ('drop_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('driver_assigned', 'Driver Assigned'), ('picked_up', 'Picked Up'), ('in_service', 'In Service'), ('delivered', 'Delivered')], default='pending', max_length=20)),
                ('pickup_notes', models.TextField(blank=True, null=True)),
                ('drop_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pickup_request', to='bookings.booking')),
            ],
            options={
                'verbose_name': 'Pickup/Drop Request',
                'verbose_name_plural': 'Pickup/Drop Requests',
                'db_table': 'pickup_drop_requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
