# Generated by Django 5.0.1 on 2025-11-19 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pickup', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pickupdroprequest',
            name='request_type',
            field=models.CharField(choices=[('pickup', 'Pickup'), ('drop', 'Drop')], default='pickup', max_length=10),
        ),
    ]
