# Generated by Django 5.0.1 on 2026-01-24 17:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pickup', '0003_pickupdroprequest_request_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='pickupdroprequest',
            name='driver',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'supervisor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pickup_assignments', to=settings.AUTH_USER_MODEL),
        ),
    ]
