# Generated by Django 5.0.1 on 2025-11-20 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_tax_rate', models.DecimalField(decimal_places=2, default=0, help_text='Default tax percentage for invoices', max_digits=5)),
                ('tax_name', models.CharField(default='GST', help_text='Tax name (e.g., GST, VAT)', max_length=50)),
                ('business_name', models.CharField(blank=True, max_length=255, null=True)),
                ('business_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('business_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('business_address', models.TextField(blank=True, null=True)),
                ('currency', models.CharField(default='INR', help_text='Currency code (e.g., USD, INR)', max_length=10)),
                ('currency_symbol', models.CharField(default='₹', max_length=5)),
                ('booking_advance_days', models.IntegerField(default=30, help_text='Maximum days in advance for booking')),
                ('cancellation_hours', models.IntegerField(default=24, help_text='Minimum hours before cancellation allowed')),
                ('slot_duration_minutes', models.IntegerField(default=60, help_text='Duration of each booking slot in minutes')),
                ('enable_email_notifications', models.BooleanField(default=True)),
                ('enable_sms_notifications', models.BooleanField(default=False)),
                ('maintenance_mode', models.BooleanField(default=False, help_text='Put system in maintenance mode')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Global Settings',
                'verbose_name_plural': 'Global Settings',
                'db_table': 'global_settings',
            },
        ),
    ]
