# Generated by Django 5.0.1 on 2026-01-24 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='K3 CAR CARE', max_length=255)),
                ('branch_name', models.CharField(blank=True, help_text='e.g., CHANDPUR', max_length=255)),
                ('logo', models.ImageField(blank=True, help_text='Company logo for invoices', null=True, upload_to='company/logos/')),
                ('address_line1', models.CharField(help_text='Street address', max_length=255)),
                ('address_line2', models.CharField(blank=True, help_text='Additional address info', max_length=255)),
                ('city', models.CharField(default='Varanasi', max_length=100)),
                ('state', models.CharField(default='Uttar Pradesh', max_length=100)),
                ('pincode', models.CharField(default='221103', max_length=10)),
                ('phone', models.CharField(help_text='Primary contact number', max_length=20)),
                ('email', models.EmailField(help_text='Company email', max_length=254)),
                ('website', models.URLField(blank=True, help_text='Company website')),
                ('gst_number', models.CharField(help_text='GST registration number', max_length=20)),
                ('pan_number', models.CharField(blank=True, help_text='PAN number', max_length=10)),
                ('bank_name', models.CharField(help_text='Bank name', max_length=100)),
                ('account_number', models.CharField(help_text='Bank account number', max_length=50)),
                ('ifsc_code', models.CharField(help_text='IFSC code', max_length=15)),
                ('account_holder_name', models.CharField(help_text='Account holder name', max_length=255)),
                ('branch_address', models.CharField(blank=True, help_text='Bank branch address', max_length=255)),
                ('terms_and_conditions', models.TextField(default='1. Goods once sold will not be taken back or exchanged\n2. All disputes are subject to jurisdiction only', help_text='Terms and conditions to display on invoice')),
                ('footer_message', models.CharField(default='****THANK YOU. PLEASE VISIT AGAIN****', help_text='Footer message on invoice', max_length=255)),
                ('invoice_prefix', models.CharField(default='B2C', help_text='Prefix for invoice numbers (e.g., B2C, B2B)', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Company Settings',
                'verbose_name_plural': 'Company Settings',
                'db_table': 'company_settings',
            },
        ),
    ]
