# Generated by Django 5.0.1 on 2026-02-03 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0002_companysettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferralSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=True, help_text='Enable or disable the referral program')),
                ('referrer_reward_type', models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed Amount')], default='fixed', help_text='Type of reward for the referrer', max_length=20)),
                ('referrer_reward_value', models.DecimalField(decimal_places=2, default=100.0, help_text='Reward value (percentage or fixed amount in ₹)', max_digits=10)),
                ('referee_reward_type', models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed Amount')], default='fixed', help_text='Type of reward for the referee', max_length=20)),
                ('referee_reward_value', models.DecimalField(decimal_places=2, default=100.0, help_text='Reward value (percentage or fixed amount in ₹)', max_digits=10)),
                ('minimum_job_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Minimum job amount to qualify for referral rewards (0 = no minimum)', max_digits=10)),
                ('max_referrer_reward_cap', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum reward cap for percentage-based referrer rewards', max_digits=10, null=True)),
                ('max_referee_reward_cap', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum reward cap for percentage-based referee rewards', max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Referral Settings',
                'verbose_name_plural': 'Referral Settings',
                'db_table': 'referral_settings',
            },
        ),
    ]
