# Generated by Django 5.0.1 on 2025-11-16 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobCardPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_type', models.CharField(choices=[('before', 'Before'), ('after', 'After')], max_length=10)),
                ('image', models.ImageField(upload_to='jobcard_photos/')),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Job Card Photo',
                'verbose_name_plural': 'Job Card Photos',
                'db_table': 'job_card_photos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PartUsed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_name', models.CharField(max_length=200)),
                ('quantity', models.IntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Part Used',
                'verbose_name_plural': 'Parts Used',
                'db_table': 'parts_used',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('assigned', 'Assigned'), ('started', 'Started'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='assigned', max_length=20)),
                ('technician_notes', models.TextField(blank=True, null=True)),
                ('estimated_delivery_time', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='jobcard', to='bookings.booking')),
            ],
            options={
                'verbose_name': 'Job Card',
                'verbose_name_plural': 'Job Cards',
                'db_table': 'job_cards',
                'ordering': ['-created_at'],
            },
        ),
    ]
