# Generated by Django 5.0.1 on 2025-11-16 11:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobcards', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcard',
            name='technician',
            field=models.ForeignKey(limit_choices_to={'role': 'staff'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobcards', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jobcardphoto',
            name='jobcard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='jobcards.jobcard'),
        ),
        migrations.AddField(
            model_name='partused',
            name='jobcard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts_used', to='jobcards.jobcard'),
        ),
    ]
