# Generated by Django 5.0.1 on 2025-11-17 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0001_initial'),
        ('jobcards', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcard',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobcards', to='branches.branch'),
        ),
    ]
