# Generated by Django 5.0.1 on 2025-11-28 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobcards', '0003_jobcard_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcard',
            name='allowed_duration_minutes',
            field=models.IntegerField(blank=True, help_text='Time allocated for this job in minutes. Defaults to package duration if not set.', null=True),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='job_started_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when technician actually started the job', null=True),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='overdue_notification_sent',
            field=models.BooleanField(default=False, help_text='Track if overdue notification has been sent'),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='warning_sent',
            field=models.BooleanField(default=False, help_text='Track if 5-minute warning notification has been sent'),
        ),
    ]
