# Generated by Django 5.0.1 on 2025-12-02 03:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_initial'),
        ('jobcards', '0004_jobcard_allowed_duration_minutes_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcard',
            name='applicator_team',
            field=models.ManyToManyField(blank=True, help_text='Applicator team members assigned to execute the work', limit_choices_to={'role': 'supervisor'}, related_name='applicator_jobcards', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='floor_manager',
            field=models.ForeignKey(blank=True, help_text='Floor Manager / QC Manager assigned to this job', limit_choices_to={'role': 'floor_manager'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='floor_manager_jobcards', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='supervisor',
            field=models.ForeignKey(blank=True, help_text='Supervisor assigned to review and approve this job', limit_choices_to={'role': 'supervisor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervisor_jobcards', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='jobcard',
            name='status',
            field=models.CharField(choices=[('created', 'Job Card Created'), ('qc_pending', 'QC Pending'), ('qc_completed', 'QC Completed'), ('qc_rejected', 'QC Rejected'), ('supervisor_approved', 'Supervisor Approved'), ('assigned_to_applicator', 'Assigned to Applicator Team'), ('work_in_progress', 'Work In Progress'), ('work_completed', 'Work Completed'), ('final_qc_pending', 'Final QC Pending'), ('final_qc_passed', 'Final QC Passed'), ('final_qc_failed', 'Final QC Failed'), ('customer_approval_pending', 'Customer Approval Pending'), ('customer_approved', 'Customer Approved'), ('customer_revision_requested', 'Customer Revision Requested'), ('ready_for_billing', 'Ready for Billing'), ('billed', 'Billed'), ('delivered', 'Delivered'), ('closed', 'Closed')], default='created', max_length=30),
        ),
        migrations.AlterField(
            model_name='jobcard',
            name='technician',
            field=models.ForeignKey(blank=True, help_text='Legacy field - use supervisor instead', limit_choices_to={'role': 'supervisor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobcards', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='jobcardphoto',
            name='photo_type',
            field=models.CharField(choices=[('before', 'Before'), ('after', 'After'), ('in_progress', 'In Progress'), ('initial', 'Initial Check-in')], max_length=20),
        ),
        migrations.CreateModel(
            name='CustomerApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('revision_requested', 'Revision Requested')], default='pending', max_length=20)),
                ('approval_notes', models.TextField(blank=True, null=True)),
                ('revision_notes', models.TextField(blank=True, help_text='Customer notes for requested revisions', null=True)),
                ('photos_viewed', models.BooleanField(default=False)),
                ('tasks_reviewed', models.BooleanField(default=False)),
                ('qc_report_viewed', models.BooleanField(default=False)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_approvals', to='customers.customer')),
                ('jobcard', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer_approval', to='jobcards.jobcard')),
            ],
            options={
                'verbose_name': 'Customer Approval',
                'verbose_name_plural': 'Customer Approvals',
                'db_table': 'customer_approvals',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FinalQCReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('passed', 'Passed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('after_photos', models.JSONField(blank=True, default=list, help_text='After photos taken during final QC')),
                ('checklist_verified', models.BooleanField(default=False, help_text='All checklist items verified')),
                ('parts_verified', models.BooleanField(default=False, help_text='Parts used match job card')),
                ('quality_notes', models.TextField(blank=True, null=True)),
                ('issues_found', models.TextField(blank=True, help_text='Issues found during final QC', null=True)),
                ('failure_reason', models.TextField(blank=True, help_text='Reason for failure if failed', null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('jobcard', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='final_qc_report', to='jobcards.jobcard')),
                ('supervisor', models.ForeignKey(limit_choices_to={'role': 'supervisor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='final_qc_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Final QC Report',
                'verbose_name_plural': 'Final QC Reports',
                'db_table': 'final_qc_reports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QCReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scratches', models.TextField(blank=True, help_text='Scratches noted during inspection', null=True)),
                ('dents', models.TextField(blank=True, help_text='Dents noted during inspection', null=True)),
                ('before_photos', models.JSONField(blank=True, default=list, help_text='Before photos taken during QC')),
                ('checklist_points', models.JSONField(blank=True, default=list, help_text='Checklist items to be completed')),
                ('required_parts', models.JSONField(blank=True, default=list, help_text='Parts required for the job')),
                ('additional_tasks', models.TextField(blank=True, help_text='Additional tasks identified (upselling opportunity)', null=True)),
                ('additional_tasks_price', models.DecimalField(decimal_places=2, default=0, help_text='Estimated price for additional tasks', max_digits=10)),
                ('notes', models.TextField(blank=True, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('floor_manager', models.ForeignKey(limit_choices_to={'role': 'floor_manager'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qc_reports', to=settings.AUTH_USER_MODEL)),
                ('jobcard', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='qc_report', to='jobcards.jobcard')),
            ],
            options={
                'verbose_name': 'QC Report',
                'verbose_name_plural': 'QC Reports',
                'db_table': 'qc_reports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SupervisorReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('review_notes', models.TextField(blank=True, null=True)),
                ('stock_availability_checked', models.BooleanField(default=False)),
                ('pricing_confirmed', models.BooleanField(default=False)),
                ('rejection_reason', models.TextField(blank=True, help_text='Reason for rejection if rejected', null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('jobcard', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='supervisor_review', to='jobcards.jobcard')),
                ('supervisor', models.ForeignKey(limit_choices_to={'role': 'supervisor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervisor_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Supervisor Review',
                'verbose_name_plural': 'Supervisor Reviews',
                'db_table': 'supervisor_reviews',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VehicleDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_notes', models.TextField(blank=True, null=True)),
                ('customer_satisfaction_confirmed', models.BooleanField(default=False)),
                ('keys_delivered', models.BooleanField(default=False)),
                ('final_walkthrough_completed', models.BooleanField(default=False)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('delivered_by', models.ForeignKey(help_text='Staff member who delivered the vehicle', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries', to=settings.AUTH_USER_MODEL)),
                ('jobcard', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery', to='jobcards.jobcard')),
            ],
            options={
                'verbose_name': 'Vehicle Delivery',
                'verbose_name_plural': 'Vehicle Deliveries',
                'db_table': 'vehicle_deliveries',
                'ordering': ['-created_at'],
            },
        ),
    ]
