# Generated by Django 5.0.1 on 2025-12-04 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobcards', '0005_jobcard_applicator_team_jobcard_floor_manager_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcard',
            name='service_checklist',
            field=models.JSONField(blank=True, default=list, help_text='Service checklist items for work execution'),
        ),
    ]
