# Generated by Django 5.0.1 on 2025-12-06 05:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobcards', '0006_jobcard_service_checklist'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobcard',
            name='applicator_team',
            field=models.ManyToManyField(blank=True, help_text='Applicator team members assigned to execute the work', limit_choices_to={'role': 'applicator'}, related_name='applicator_jobcards', to=settings.AUTH_USER_MODEL),
        ),
    ]
