# Generated by Django 5.0.1 on 2025-12-06 06:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobcards', '0007_alter_jobcard_applicator_team'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicatorTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_description', models.TextField(help_text='Description of the specific task assigned to this applicator')),
                ('supervisor_notes', models.TextField(blank=True, help_text='Notes added by supervisor for this task', null=True)),
                ('started_at', models.DateTimeField(blank=True, help_text='When this specific task was started', null=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='When this specific task was completed', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this task is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applicator', models.ForeignKey(limit_choices_to={'role': 'applicator'}, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL)),
                ('jobcard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applicator_tasks', to='jobcards.jobcard')),
            ],
            options={
                'verbose_name': 'Applicator Task',
                'verbose_name_plural': 'Applicator Tasks',
                'db_table': 'applicator_tasks',
                'ordering': ['-created_at'],
            },
        ),
    ]
