# Generated by Django 4.2.7 on 2025-12-10 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobcards', '0009_add_floor_manager_statuses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobcard',
            name='status',
            field=models.CharField(choices=[('created', 'Job Card Created'), ('qc_pending', 'QC Pending'), ('qc_completed', 'QC Completed'), ('qc_rejected', 'QC Rejected'), ('supervisor_approved', 'Supervisor Approved'), ('supervisor_rejected', 'Supervisor Rejected'), ('floor_manager_confirmed', 'Floor Manager Confirmed'), ('assigned_to_applicator', 'Assigned to Applicator Team'), ('work_in_progress', 'Work In Progress'), ('work_completed', 'Work Completed'), ('final_qc_pending', 'Final QC Pending'), ('final_qc_passed', 'Final QC Passed'), ('final_qc_failed', 'Final QC Failed'), ('floor_manager_final_qc_confirmed', 'Floor Manager Final QC Confirmed'), ('customer_approval_pending', 'Customer Approval Pending'), ('customer_approved', 'Customer Approved'), ('customer_revision_requested', 'Customer Revision Requested'), ('ready_for_billing', 'Ready for Billing'), ('billed', 'Billed'), ('delivered', 'Delivered'), ('closed', 'Closed')], default='created', max_length=50),
        ),
    ]