# Generated by Django 5.0.1 on 2025-12-14 07:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobcards', '0011_alter_jobcard_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DynamicTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('estimated_price', models.DecimalField(decimal_places=2, default=0, help_text='Estimated price for this extra task', max_digits=10)),
                ('requires_approval', models.BooleanField(default=True, help_text='Requires customer approval before execution')),
                ('approved_by_customer', models.BooleanField(default=False)),
                ('approval_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_dynamic_tasks', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_dynamic_tasks', to=settings.AUTH_USER_MODEL)),
                ('jobcard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dynamic_tasks', to='jobcards.jobcard')),
            ],
            options={
                'verbose_name': 'Dynamic Task',
                'verbose_name_plural': 'Dynamic Tasks',
                'db_table': 'dynamic_tasks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobCardActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('status_change', 'Status Changed'), ('note_added', 'Note Added'), ('task_added', 'Task Added'), ('task_updated', 'Task Updated'), ('photo_uploaded', 'Photo Uploaded'), ('assignment', 'Team Assignment'), ('approval', 'Approval/Rejection'), ('qc_completed', 'QC Completed'), ('work_started', 'Work Started'), ('work_completed', 'Work Completed')], max_length=30)),
                ('description', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional activity data in JSON format')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('jobcard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='jobcards.jobcard')),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performed_activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Job Card Activity',
                'verbose_name_plural': 'Job Card Activities',
                'db_table': 'job_card_activities',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobCardNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_type', models.CharField(choices=[('internal', 'Internal Note'), ('customer', 'Customer Note'), ('task', 'Task Note'), ('issue', 'Issue/Problem'), ('reminder', 'Reminder')], default='internal', max_length=20)),
                ('content', models.TextField()),
                ('is_pinned', models.BooleanField(default=False, help_text='Pin important notes to top')),
                ('visible_to_customer', models.BooleanField(default=False, help_text='Show this note to customer')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_notes', to=settings.AUTH_USER_MODEL)),
                ('jobcard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='jobcards.jobcard')),
            ],
            options={
                'verbose_name': 'Job Card Note',
                'verbose_name_plural': 'Job Card Notes',
                'db_table': 'job_card_notes',
                'ordering': ['-is_pinned', '-created_at'],
            },
        ),
    ]
