# Generated by Django 5.0.1 on 2025-12-20 20:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_employeesalarystructure_payroll_pettycash_and_more'),
        ('branches', '0002_branch_google_review_url'),
        ('jobcards', '0012_dynamictask_jobcardactivity_jobcardnote'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RewardSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier_1_minutes', models.IntegerField(default=15, help_text='Minutes early for tier 1 reward')),
                ('tier_1_amount', models.DecimalField(decimal_places=2, default=100, help_text='Reward amount for tier 1', max_digits=10)),
                ('tier_2_minutes', models.IntegerField(default=30, help_text='Minutes early for tier 2 reward')),
                ('tier_2_amount', models.DecimalField(decimal_places=2, default=200, help_text='Reward amount for tier 2', max_digits=10)),
                ('tier_3_minutes', models.IntegerField(default=45, help_text='Minutes early for tier 3 reward')),
                ('tier_3_amount', models.DecimalField(decimal_places=2, default=300, help_text='Reward amount for tier 3', max_digits=10)),
                ('deduction_enabled', models.BooleanField(default=True)),
                ('deduction_threshold_minutes', models.IntegerField(default=15, help_text='Minutes late before deduction applies')),
                ('deduction_per_minute', models.DecimalField(decimal_places=2, default=5, help_text='Deduction amount per minute late', max_digits=10)),
                ('max_deduction_per_job', models.DecimalField(decimal_places=2, default=500, help_text='Maximum deduction per job', max_digits=10)),
                ('applicator_share_percentage', models.DecimalField(decimal_places=2, default=50.0, help_text='Default percentage of reward to distribute to applicator team (0-100)', max_digits=5)),
                ('apply_deduction_to_applicators', models.BooleanField(default=True, help_text='Whether deductions also apply to applicator team members')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(blank=True, help_text='Branch-specific settings, null for global settings', null=True, on_delete=django.db.models.deletion.CASCADE, to='branches.branch')),
            ],
            options={
                'verbose_name': 'Reward Settings',
                'verbose_name_plural': 'Reward Settings',
                'db_table': 'reward_settings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SupervisorReward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('reward', 'Reward'), ('deduction', 'Deduction')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('allowed_duration_minutes', models.IntegerField(help_text='Allowed job duration')),
                ('actual_duration_minutes', models.IntegerField(help_text='Actual job duration')),
                ('time_difference_minutes', models.IntegerField(help_text='Difference (negative = early, positive = late)')),
                ('tier', models.CharField(blank=True, help_text='Reward tier (tier_1, tier_2, tier_3)', max_length=50, null=True)),
                ('calculation_notes', models.TextField(blank=True, null=True)),
                ('split_percentage', models.DecimalField(blank=True, decimal_places=2, help_text='Custom split percentage for this applicator (overrides default)', max_digits=5, null=True)),
                ('is_applicator_share', models.BooleanField(default=False, help_text="True if this is an applicator's share")),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_rewards', to=settings.AUTH_USER_MODEL)),
                ('jobcard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rewards', to='jobcards.jobcard')),
                ('payroll', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rewards', to='accounting.payroll')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_rewards', to=settings.AUTH_USER_MODEL)),
                ('supervisor_reward', models.ForeignKey(blank=True, help_text="Reference to supervisor's reward if this is an applicator share", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applicator_shares', to='jobcards.supervisorreward')),
            ],
            options={
                'verbose_name': 'Supervisor Reward',
                'verbose_name_plural': 'Supervisor Rewards',
                'db_table': 'supervisor_rewards',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'status'], name='supervisor__recipie_3cabb7_idx'), models.Index(fields=['jobcard', 'transaction_type'], name='supervisor__jobcard_e728dc_idx'), models.Index(fields=['created_at'], name='supervisor__created_ef4087_idx')],
            },
        ),
    ]
