# Generated by Django 5.0.1 on 2026-01-01 17:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0002_branch_google_review_url'),
        ('jobcards', '0013_rewardsettings_supervisorreward'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Template name (e.g., 'Standard Detailing', 'Quick Wash')", max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('service_category', models.CharField(blank=True, help_text="If set, applies to services of this category (e.g., 'detailing', 'wash', 'coating')", max_length=50, null=True)),
                ('is_default', models.BooleanField(default=False, help_text='If true, this is the default template when no specific match is found')),
                ('is_active', models.BooleanField(default=True)),
                ('skip_customer_approval', models.BooleanField(default=False, help_text='Skip customer approval step (e.g., for walk-in customers)')),
                ('skip_floor_manager_final_qc', models.BooleanField(default=False, help_text='Skip floor manager final QC approval (for smaller operations)')),
                ('require_supervisor_review', models.BooleanField(default=True, help_text='Require supervisor to review QC before work starts')),
                ('auto_assign_applicators', models.BooleanField(default=False, help_text='Auto-assign applicators based on availability')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(blank=True, help_text='If set, this template applies only to this branch', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workflow_templates', to='branches.branch')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_workflow_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Workflow Template',
                'verbose_name_plural': 'Workflow Templates',
                'db_table': 'workflow_templates',
                'ordering': ['-is_default', 'name'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_code', models.CharField(help_text="Internal status code (e.g., 'qc_pending', 'work_in_progress')", max_length=50)),
                ('display_name', models.CharField(help_text='User-friendly display name', max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('status_type', models.CharField(choices=[('initial', 'Initial'), ('qc', 'Quality Check'), ('approval', 'Approval'), ('work', 'Work Execution'), ('final_qc', 'Final QC'), ('customer', 'Customer Action'), ('billing', 'Billing'), ('delivery', 'Delivery'), ('terminal', 'Terminal/Closed')], default='work', max_length=20)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order in the workflow')),
                ('is_active_status', models.BooleanField(default=True, help_text='If false, this status is skipped in this workflow')),
                ('is_terminal', models.BooleanField(default=False, help_text='Terminal status (job complete or cancelled)')),
                ('max_duration_hours', models.PositiveIntegerField(blank=True, help_text='Maximum time job should stay in this status', null=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to='jobcards.workflowtemplate')),
            ],
            options={
                'verbose_name': 'Workflow Status',
                'verbose_name_plural': 'Workflow Statuses',
                'db_table': 'workflow_statuses',
                'ordering': ['template', 'order'],
            },
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=20)),
                ('can_view_all_jobs', models.BooleanField(default=False)),
                ('can_view_branch_jobs', models.BooleanField(default=True)),
                ('can_view_assigned_jobs', models.BooleanField(default=True)),
                ('can_create_jobcard', models.BooleanField(default=False)),
                ('can_assign_staff', models.BooleanField(default=False)),
                ('can_perform_qc', models.BooleanField(default=False)),
                ('can_approve_qc', models.BooleanField(default=False)),
                ('can_execute_work', models.BooleanField(default=False)),
                ('can_perform_final_qc', models.BooleanField(default=False)),
                ('can_generate_invoice', models.BooleanField(default=False)),
                ('can_deliver_vehicle', models.BooleanField(default=False)),
                ('can_close_job', models.BooleanField(default=False)),
                ('inherits_from', models.CharField(blank=True, help_text='Inherit all permissions from this role', max_length=20, null=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_permissions', to='jobcards.workflowtemplate')),
            ],
            options={
                'verbose_name': 'Role Permission',
                'verbose_name_plural': 'Role Permissions',
                'db_table': 'role_permissions',
            },
        ),
        migrations.CreateModel(
            name='WorkflowTransition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(help_text='Source status code', max_length=50)),
                ('to_status', models.CharField(help_text='Target status code', max_length=50)),
                ('action_name', models.CharField(help_text="Name of the action (e.g., 'Complete QC', 'Start Work')", max_length=100)),
                ('action_description', models.TextField(blank=True, null=True)),
                ('allowed_roles', models.JSONField(default=list, help_text='List of roles that can perform this transition')),
                ('requires_assignment', models.BooleanField(default=True, help_text='User must be assigned to the job to perform this transition')),
                ('requires_notes', models.BooleanField(default=False, help_text='Notes/reason required for this transition')),
                ('requires_photos', models.BooleanField(default=False, help_text='Photos required for this transition')),
                ('condition_field', models.CharField(blank=True, help_text="Field to check for conditional transition (e.g., 'qc_report.is_completed')", max_length=100, null=True)),
                ('condition_value', models.CharField(blank=True, help_text='Required value for the condition field', max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transitions', to='jobcards.workflowtemplate')),
            ],
            options={
                'verbose_name': 'Workflow Transition',
                'verbose_name_plural': 'Workflow Transitions',
                'db_table': 'workflow_transitions',
                'ordering': ['template', 'from_status', 'to_status'],
            },
        ),
        migrations.AddConstraint(
            model_name='workflowtemplate',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('branch', 'service_category', 'is_default'), name='unique_default_template'),
        ),
        migrations.AlterUniqueTogether(
            name='workflowstatus',
            unique_together={('template', 'status_code')},
        ),
        migrations.AlterUniqueTogether(
            name='rolepermission',
            unique_together={('template', 'role')},
        ),
        migrations.AlterUniqueTogether(
            name='workflowtransition',
            unique_together={('template', 'from_status', 'to_status')},
        ),
    ]
