# Generated by Django 5.0.1 on 2026-01-03 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobcards', '0014_workflow_config'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workflowtransition',
            options={'ordering': ['template', 'order', 'from_status'], 'verbose_name': 'Workflow Transition', 'verbose_name_plural': 'Workflow Transitions'},
        ),
        migrations.AddField(
            model_name='workflowtransition',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Order of this transition in the workflow sequence'),
        ),
    ]
