# Generated by Django 5.0.1 on 2026-01-05 17:52

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0002_branch_google_review_url'),
        ('jobcards', '0015_add_transition_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='partused',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Cost price per unit (for profit calculation)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='partused',
            name='part_name',
            field=models.CharField(help_text='Part name (auto-filled from catalog or manual entry)', max_length=200),
        ),
        migrations.AlterField(
            model_name='partused',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Selling price per unit (charged to customer)', max_digits=10),
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Part name', max_length=200)),
                ('sku', models.CharField(help_text='Stock Keeping Unit (unique identifier)', max_length=50, unique=True)),
                ('category', models.CharField(choices=[('consumable', 'Consumable'), ('spare', 'Spare Part'), ('material', 'Material'), ('chemical', 'Chemical/Product'), ('tool', 'Tool/Equipment')], default='spare', max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('cost_price', models.DecimalField(decimal_places=2, help_text='Purchase/cost price per unit', max_digits=10)),
                ('selling_price', models.DecimalField(decimal_places=2, help_text='Selling price per unit (charged to customer)', max_digits=10)),
                ('stock', models.IntegerField(default=0, help_text='Current stock quantity')),
                ('min_stock_level', models.IntegerField(default=5, help_text='Minimum stock level for alerts')),
                ('unit', models.CharField(choices=[('pieces', 'Pieces'), ('liters', 'Liters'), ('kg', 'Kilograms'), ('sets', 'Sets'), ('meters', 'Meters'), ('bottles', 'Bottles')], default='pieces', max_length=20)),
                ('gst_applicable', models.BooleanField(default=True, help_text='Whether GST is applicable')),
                ('gst_rate', models.DecimalField(decimal_places=2, default=Decimal('18.00'), help_text='GST percentage (e.g., 18.00 for 18%)', max_digits=5)),
                ('hsn_code', models.CharField(blank=True, help_text='HSN code for GST', max_length=20, null=True)),
                ('is_global', models.BooleanField(default=True, help_text='If True, available to all branches')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(blank=True, help_text='Specific branch (only if is_global=False)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='branches.branch')),
            ],
            options={
                'verbose_name': 'Part',
                'verbose_name_plural': 'Parts',
                'db_table': 'parts',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='partused',
            name='part',
            field=models.ForeignKey(blank=True, help_text='Part from catalog (if used)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usage_records', to='jobcards.part'),
        ),
        migrations.AddIndex(
            model_name='part',
            index=models.Index(fields=['sku'], name='parts_sku_24d5db_idx'),
        ),
        migrations.AddIndex(
            model_name='part',
            index=models.Index(fields=['category'], name='parts_categor_c0361c_idx'),
        ),
        migrations.AddIndex(
            model_name='part',
            index=models.Index(fields=['is_active'], name='parts_is_acti_7b1503_idx'),
        ),
    ]
