# Generated by Django 5.0.1 on 2026-01-06 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobcards', '0016_partused_cost_price_alter_partused_part_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rolepermission',
            name='can_add_parts',
            field=models.BooleanField(default=False),
        ),
    ]
