# Generated by Django 5.0.1 on 2026-01-06 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobcards', '0017_rolepermission_can_add_parts'),
    ]

    operations = [
        migrations.AddField(
            model_name='rolepermission',
            name='can_manage_parts_inventory',
            field=models.BooleanField(default=False, help_text='Can manage parts catalog and inventory'),
        ),
        migrations.AlterField(
            model_name='rolepermission',
            name='can_add_parts',
            field=models.BooleanField(default=False, help_text='Can add parts to job cards'),
        ),
    ]
