# Generated by Django 5.0.1 on 2026-01-09 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobcards', '0018_add_manage_parts_inventory_permission'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcard',
            name='warning_10min_sent',
            field=models.BooleanField(default=False, help_text='Track if 10-minute warning has been sent'),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='warning_15min_sent',
            field=models.BooleanField(default=False, help_text='Track if 15-minute warning has been sent'),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='warning_1min_sent',
            field=models.BooleanField(default=False, help_text='Track if 1-minute warning has been sent'),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='warning_3min_sent',
            field=models.BooleanField(default=False, help_text='Track if 3-minute warning has been sent'),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='warning_5min_sent',
            field=models.BooleanField(default=False, help_text='Track if 5-minute warning has been sent'),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='warning_7min_sent',
            field=models.BooleanField(default=False, help_text='Track if 7-minute warning has been sent'),
        ),
        migrations.AlterField(
            model_name='jobcard',
            name='warning_sent',
            field=models.BooleanField(default=False, help_text='Track if 10-minute warning notification has been sent (legacy)'),
        ),
    ]
