# Generated by Django 5.0.1 on 2026-01-10 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobcards', '0019_jobcard_warning_10min_sent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcard',
            name='warning_2min_sent',
            field=models.BooleanField(default=False, help_text='Track if 2-minute warning has been sent'),
        ),
    ]
