# Generated by Django 5.0.1 on 2026-01-31 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobcards', '0021_add_timer_buffer_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='rewardsettings',
            name='apply_time_bonus',
            field=models.BooleanField(default=True, help_text='Apply additional bonus percentage for time saved'),
        ),
        migrations.AddField(
            model_name='rewardsettings',
            name='tier_1_job_value_min',
            field=models.DecimalField(decimal_places=2, default=5000, help_text='Minimum job value for tier 1 percentage reward', max_digits=10),
        ),
        migrations.AddField(
            model_name='rewardsettings',
            name='tier_1_reward_percentage',
            field=models.DecimalField(decimal_places=2, default=1.0, help_text='Reward percentage for tier 1 (e.g., 1.00 = 1%)', max_digits=5),
        ),
        migrations.AddField(
            model_name='rewardsettings',
            name='tier_2_job_value_min',
            field=models.DecimalField(decimal_places=2, default=10000, help_text='Minimum job value for tier 2 percentage reward', max_digits=10),
        ),
        migrations.AddField(
            model_name='rewardsettings',
            name='tier_2_reward_percentage',
            field=models.DecimalField(decimal_places=2, default=1.5, help_text='Reward percentage for tier 2 (e.g., 1.50 = 1.5%)', max_digits=5),
        ),
        migrations.AddField(
            model_name='rewardsettings',
            name='tier_3_job_value_min',
            field=models.DecimalField(decimal_places=2, default=12000, help_text='Minimum job value for tier 3 percentage reward', max_digits=10),
        ),
        migrations.AddField(
            model_name='rewardsettings',
            name='tier_3_reward_percentage',
            field=models.DecimalField(decimal_places=2, default=1.8, help_text='Reward percentage for tier 3 (e.g., 1.80 = 1.8%)', max_digits=5),
        ),
        migrations.AddField(
            model_name='rewardsettings',
            name='tier_4_job_value_min',
            field=models.DecimalField(decimal_places=2, default=15000, help_text='Minimum job value for tier 4 percentage reward', max_digits=10),
        ),
        migrations.AddField(
            model_name='rewardsettings',
            name='tier_4_reward_percentage',
            field=models.DecimalField(decimal_places=2, default=2.0, help_text='Reward percentage for tier 4 (e.g., 2.00 = 2%)', max_digits=5),
        ),
        migrations.AddField(
            model_name='rewardsettings',
            name='time_bonus_interval_minutes',
            field=models.IntegerField(default=15, help_text='Time interval in minutes for applying bonus (default: 15 min)'),
        ),
        migrations.AddField(
            model_name='rewardsettings',
            name='time_bonus_percentage',
            field=models.DecimalField(decimal_places=2, default=0.5, help_text='Additional percentage for every 15 minutes saved (e.g., 0.50 = 0.5%)', max_digits=5),
        ),
        migrations.AddField(
            model_name='rewardsettings',
            name='use_percentage_based_rewards',
            field=models.BooleanField(default=False, help_text='Use percentage of job value instead of fixed amounts'),
        ),
    ]
