# Generated by Django 5.0.1 on 2026-01-31 18:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0002_branch_google_review_url'),
        ('jobcards', '0022_rewardsettings_apply_time_bonus_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerformanceMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_duration_minutes', models.IntegerField(help_text='Scheduled/allowed duration for the job')),
                ('actual_duration_minutes', models.IntegerField(help_text='Actual time taken to complete the job')),
                ('time_difference_minutes', models.IntegerField(help_text='Positive = saved time, Negative = delayed')),
                ('job_value', models.DecimalField(decimal_places=2, help_text='Total job value (package + add-ons + parts)', max_digits=10)),
                ('package_value', models.DecimalField(decimal_places=2, help_text='Base package value', max_digits=10)),
                ('addons_value', models.DecimalField(decimal_places=2, default=0, help_text='Total add-ons value', max_digits=10)),
                ('parts_value', models.DecimalField(decimal_places=2, default=0, help_text='Total parts value', max_digits=10)),
                ('completed_on_time', models.BooleanField(default=True, help_text='Whether job was completed within scheduled time')),
                ('quality_score', models.IntegerField(blank=True, help_text='Quality score from QC (1-10 scale)', null=True)),
                ('customer_satisfaction', models.IntegerField(blank=True, help_text='Customer satisfaction rating (1-10 scale)', null=True)),
                ('reward_amount', models.DecimalField(decimal_places=2, default=0, help_text='Total reward amount for this job', max_digits=10)),
                ('reward_percentage', models.DecimalField(blank=True, decimal_places=2, help_text='Reward percentage applied (if percentage-based)', max_digits=5, null=True)),
                ('job_started_at', models.DateTimeField()),
                ('job_completed_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applicators', models.ManyToManyField(blank=True, limit_choices_to={'role': 'applicator'}, related_name='applicator_performance', to=settings.AUTH_USER_MODEL)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_performances', to='branches.branch')),
                ('floor_manager', models.ForeignKey(blank=True, limit_choices_to={'role': 'floor_manager'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fm_performance', to=settings.AUTH_USER_MODEL)),
                ('jobcard', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='performance', to='jobcards.jobcard')),
                ('supervisor', models.ForeignKey(blank=True, limit_choices_to={'role': 'supervisor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervisor_performance', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Job Card Performance Metric',
                'verbose_name_plural': 'Job Card Performance Metrics',
                'db_table': 'jobcard_performance_metrics',
                'ordering': ['-job_completed_at'],
                'indexes': [models.Index(fields=['branch', 'job_completed_at'], name='jobcard_per_branch__4164f8_idx'), models.Index(fields=['supervisor', 'job_completed_at'], name='jobcard_per_supervi_e8150e_idx'), models.Index(fields=['floor_manager', 'job_completed_at'], name='jobcard_per_floor_m_052e46_idx'), models.Index(fields=['completed_on_time'], name='jobcard_per_complet_8d7a99_idx')],
            },
        ),
        migrations.CreateModel(
            name='TeamPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_type', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly')], max_length=20)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('total_jobs_completed', models.IntegerField(default=0, help_text='Total number of jobs completed in this period')),
                ('jobs_on_time', models.IntegerField(default=0, help_text='Jobs completed on or before scheduled time')),
                ('jobs_delayed', models.IntegerField(default=0, help_text='Jobs completed after scheduled time')),
                ('total_time_saved', models.IntegerField(default=0, help_text='Total minutes saved across all jobs')),
                ('total_time_delayed', models.IntegerField(default=0, help_text='Total minutes delayed across all jobs')),
                ('average_completion_time', models.DecimalField(decimal_places=2, default=0, help_text='Average job completion time in minutes', max_digits=10)),
                ('total_job_value', models.DecimalField(decimal_places=2, default=0, help_text='Total value of all jobs completed', max_digits=12)),
                ('total_rewards_earned', models.DecimalField(decimal_places=2, default=0, help_text='Total rewards earned by the team', max_digits=10)),
                ('average_reward_per_job', models.DecimalField(decimal_places=2, default=0, help_text='Average reward per job', max_digits=10)),
                ('team_members', models.JSONField(default=list, help_text='List of applicator user IDs in the team')),
                ('team_size', models.IntegerField(default=0, help_text='Number of team members')),
                ('efficiency_percentage', models.DecimalField(decimal_places=2, default=0, help_text='Overall team efficiency percentage', max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_performances', to='branches.branch')),
                ('floor_manager', models.ForeignKey(blank=True, limit_choices_to={'role': 'floor_manager'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_team_stats', to=settings.AUTH_USER_MODEL)),
                ('supervisor', models.ForeignKey(limit_choices_to={'role': 'supervisor'}, on_delete=django.db.models.deletion.CASCADE, related_name='team_stats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Team Performance',
                'verbose_name_plural': 'Team Performances',
                'db_table': 'jobcard_team_performance',
                'ordering': ['-period_start', '-total_job_value'],
                'indexes': [models.Index(fields=['branch', 'period_type', 'period_start'], name='jobcard_tea_branch__17b261_idx'), models.Index(fields=['supervisor', 'period_start'], name='jobcard_tea_supervi_571242_idx'), models.Index(fields=['period_type', 'period_start'], name='jobcard_tea_period__454b11_idx')],
                'unique_together': {('supervisor', 'period_type', 'period_start', 'period_end')},
            },
        ),
    ]
