# Generated by Django 5.0.1 on 2026-01-31 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobcards', '0023_performancemetrics_teamperformance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performancemetrics',
            name='jobcard',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='performance', to='jobcards.jobcard'),
        ),
    ]
