# Generated by Django 5.0.1 on 2026-02-01 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobcards', '0024_alter_performancemetrics_jobcard'),
    ]

    operations = [
        migrations.AddField(
            model_name='performancemetrics',
            name='gst_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='GST amount charged to customer', max_digits=10),
        ),
        migrations.AddField(
            model_name='performancemetrics',
            name='total_with_gst',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total amount customer paid (including GST)', max_digits=10),
        ),
    ]
