# Generated by Django 5.0.1 on 2026-02-06 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        ('jobcards', '0025_add_gst_to_performance'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcard',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobcards', to='companies.company'),
        ),
        migrations.AddField(
            model_name='jobcardphoto',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobcard_photos', to='companies.company'),
        ),
        migrations.AddField(
            model_name='partused',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parts_used', to='companies.company'),
        ),
    ]
