# Generated by Django 5.0.1 on 2026-02-06 19:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_add_domain_model'),
        ('jobcards', '0026_jobcard_company_jobcardphoto_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='companies.company'),
        ),
        migrations.AlterField(
            model_name='part',
            name='sku',
            field=models.CharField(help_text='Stock Keeping Unit (identifier)', max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='part',
            unique_together={('company', 'sku')},
        ),
    ]
