# Generated by Django 5.0.1 on 2026-02-06 20:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_add_domain_model'),
        ('jobcards', '0027_part_company_alter_part_sku_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rolepermission',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workflow_role_permissions', to='companies.company'),
        ),
        migrations.AddField(
            model_name='workflowstatus',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workflow_statuses', to='companies.company'),
        ),
        migrations.AddField(
            model_name='workflowtemplate',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workflow_templates', to='companies.company'),
        ),
        migrations.AddField(
            model_name='workflowtransition',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workflow_transitions', to='companies.company'),
        ),
    ]
