# Generated by Django 5.0.1 on 2026-02-07 06:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_add_domain_model'),
        ('jobcards', '0028_rolepermission_company_workflowstatus_company_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_type', models.CharField(choices=[('template_created', 'Template Created'), ('template_updated', 'Template Updated'), ('template_deleted', 'Template Deleted'), ('transition_created', 'Transition Created'), ('transition_updated', 'Transition Updated'), ('transition_deleted', 'Transition Deleted'), ('status_updated', 'Status Updated'), ('permission_updated', 'Permission Updated')], max_length=50)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('object_type', models.CharField(max_length=50)),
                ('object_id', models.IntegerField(blank=True, null=True)),
                ('old_values', models.JSONField(blank=True, default=dict)),
                ('new_values', models.JSONField(blank=True, default=dict)),
                ('change_reason', models.TextField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_changes', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workflow_change_logs', to='companies.company')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='change_logs', to='jobcards.workflowtemplate')),
            ],
            options={
                'verbose_name': 'Workflow Change Log',
                'verbose_name_plural': 'Workflow Change Logs',
                'db_table': 'workflow_change_logs',
                'ordering': ['-changed_at'],
            },
        ),
    ]
