# Generated by Django 5.0.1 on 2026-02-16 12:42

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0004_alter_servicebay_unique_together_branch_company_and_more'),
        ('companies', '0004_companysettings_whatsapp_mode'),
        ('jobcards', '0029_workflowchangelog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='stock_tracking_mode',
            field=models.CharField(choices=[('global', 'Global - Single stock pool for all branches'), ('branch', 'Branch - Track stock separately per branch')], default='global', help_text='How stock is tracked: global pool or per branch', max_length=10),
        ),
        migrations.CreateModel(
            name='BranchStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Current stock quantity at this branch', max_digits=10)),
                ('min_stock_level', models.IntegerField(default=5, help_text='Minimum stock level for this branch')),
                ('location', models.CharField(blank=True, help_text='Storage location within branch (e.g., Shelf A1, Bin 5)', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_levels', to='branches.branch')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_stocks', to='companies.company')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_stocks', to='jobcards.part')),
            ],
            options={
                'verbose_name': 'Branch Stock',
                'verbose_name_plural': 'Branch Stocks',
                'db_table': 'branch_stocks',
                'ordering': ['branch__name', 'part__name'],
                'indexes': [models.Index(fields=['branch', 'part'], name='branch_stoc_branch__fd40e1_idx'), models.Index(fields=['quantity'], name='branch_stoc_quantit_39d698_idx')],
                'unique_together': {('company', 'branch', 'part')},
            },
        ),
        migrations.CreateModel(
            name='StockTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_number', models.CharField(help_text='Auto-generated transfer number', max_length=50, unique=True)),
                ('quantity', models.DecimalField(decimal_places=2, help_text='Quantity to transfer', max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('in_transit', 'In Transit'), ('received', 'Received'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('reason', models.TextField(help_text='Reason for transfer request')),
                ('notes', models.TextField(blank=True, help_text='Additional notes', null=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('shipped_at', models.DateTimeField(blank=True, null=True)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_transfers_approved', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_transfers', to='companies.company')),
                ('from_branch', models.ForeignKey(help_text='Source branch', on_delete=django.db.models.deletion.PROTECT, related_name='stock_transfers_out', to='branches.branch')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers', to='jobcards.part')),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_transfers_received', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_transfers_requested', to=settings.AUTH_USER_MODEL)),
                ('to_branch', models.ForeignKey(help_text='Destination branch', on_delete=django.db.models.deletion.PROTECT, related_name='stock_transfers_in', to='branches.branch')),
            ],
            options={
                'verbose_name': 'Stock Transfer',
                'verbose_name_plural': 'Stock Transfers',
                'db_table': 'stock_transfers',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['transfer_number'], name='stock_trans_transfe_2376ec_idx'), models.Index(fields=['status'], name='stock_trans_status_332e43_idx'), models.Index(fields=['from_branch', 'to_branch'], name='stock_trans_from_br_612e73_idx'), models.Index(fields=['created_at'], name='stock_trans_created_487989_idx')],
            },
        ),
    ]
