# Generated by Django 5.0.1 on 2026-02-19 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobcards', '0030_add_branch_stock_tracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='partused',
            name='is_service_default',
            field=models.BooleanField(default=False, help_text='True if auto-added from service package config (cost=0 on billing)'),
        ),
    ]
