# Generated by Django 5.0.1 on 2026-02-22 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0004_alter_servicebay_unique_together_branch_company_and_more'),
        ('companies', '0004_companysettings_whatsapp_mode'),
        ('jobcards', '0032_rewardsettings_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='performancemetrics',
            name='is_paid',
            field=models.BooleanField(default=False, help_text='True once the linked invoice has been fully paid'),
        ),
        migrations.AddField(
            model_name='performancemetrics',
            name='paid_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when the invoice was marked as fully paid', null=True),
        ),
        migrations.AlterField(
            model_name='rewardsettings',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='Branch-specific override. NULL = applies to all branches in the company. When both company and branch are set, this is a branch-level override.', null=True, on_delete=django.db.models.deletion.CASCADE, to='branches.branch'),
        ),
        migrations.AddConstraint(
            model_name='rewardsettings',
            constraint=models.UniqueConstraint(fields=('company', 'branch'), name='unique_reward_settings_per_company_branch'),
        ),
    ]
