# Generated by Django 5.0.1 on 2026-02-22 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobcards', '0033_add_performance_payment_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamperformance',
            name='paid_job_value',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total value of fully-paid jobs only (confirmed revenue)', max_digits=12),
        ),
        migrations.AlterField(
            model_name='teamperformance',
            name='total_job_value',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total value of all jobs completed (estimated, includes unpaid)', max_digits=12),
        ),
    ]
