# Generated by Django 5.0.1 on 2026-02-26 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobcards', '0034_add_paid_job_value_to_teamperformance'),
        ('services', '0011_update_unique_constraint_include_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='partused',
            name='service_package',
            field=models.ForeignKey(blank=True, help_text='Service package this part was auto-deducted for', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parts_used', to='services.servicepackage'),
        ),
    ]
