# Generated by Django 5.0.1 on 2026-02-26 18:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0004_alter_servicebay_unique_together_branch_company_and_more'),
        ('jobcards', '0035_add_service_package_to_parts_used'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FloorManagerPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_type', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly')], max_length=20)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('total_jobs_completed', models.IntegerField(default=0, help_text='Total jobs completed under this floor manager')),
                ('jobs_on_time', models.IntegerField(default=0, help_text='Jobs completed on or before scheduled time')),
                ('jobs_delayed', models.IntegerField(default=0, help_text='Jobs completed after scheduled time')),
                ('total_time_saved', models.IntegerField(default=0)),
                ('total_time_delayed', models.IntegerField(default=0)),
                ('average_completion_time', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_job_value', models.DecimalField(decimal_places=2, default=0, help_text='Total value of all jobs (estimated, includes unpaid)', max_digits=12)),
                ('paid_job_value', models.DecimalField(decimal_places=2, default=0, help_text='Total value of fully-paid jobs (confirmed revenue)', max_digits=12)),
                ('total_rewards_earned', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('average_reward_per_job', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('supervised_team_ids', models.JSONField(default=list, help_text='List of supervisor user IDs managed by this floor manager')),
                ('supervised_teams_count', models.IntegerField(default=0, help_text='Number of supervisor teams under this FM')),
                ('efficiency_percentage', models.DecimalField(decimal_places=2, default=0, help_text='Overall floor-manager efficiency percentage', max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fm_performances', to='branches.branch')),
                ('floor_manager', models.ForeignKey(limit_choices_to={'role': 'floor_manager'}, on_delete=django.db.models.deletion.CASCADE, related_name='fm_perf_stats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Floor Manager Performance',
                'verbose_name_plural': 'Floor Manager Performances',
                'db_table': 'jobcard_floor_manager_performance',
                'ordering': ['-period_start', '-total_job_value'],
                'indexes': [models.Index(fields=['branch', 'period_type', 'period_start'], name='jobcard_flo_branch__d106ce_idx'), models.Index(fields=['floor_manager', 'period_start'], name='jobcard_flo_floor_m_73180c_idx'), models.Index(fields=['period_type', 'period_start'], name='jobcard_flo_period__716b15_idx')],
                'unique_together': {('floor_manager', 'period_type', 'period_start', 'period_end')},
            },
        ),
    ]
