# Generated by Django 5.0.1 on 2026-02-26 18:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0004_alter_servicebay_unique_together_branch_company_and_more'),
        ('companies', '0004_companysettings_whatsapp_mode'),
        ('jobcards', '0036_floor_manager_performance'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='floormanagerperformance',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fm_performances', to='companies.company'),
        ),
        migrations.AddField(
            model_name='performancemetrics',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_performances', to='companies.company'),
        ),
        migrations.AddField(
            model_name='teamperformance',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_performances', to='companies.company'),
        ),
        migrations.AddIndex(
            model_name='floormanagerperformance',
            index=models.Index(fields=['company', 'period_type', 'period_start'], name='jobcard_flo_company_b7c8b5_idx'),
        ),
        migrations.AddIndex(
            model_name='performancemetrics',
            index=models.Index(fields=['company', 'job_completed_at'], name='jobcard_per_company_7937a3_idx'),
        ),
        migrations.AddIndex(
            model_name='teamperformance',
            index=models.Index(fields=['company', 'period_type', 'period_start'], name='jobcard_tea_company_9a3978_idx'),
        ),
    ]
