# Generated by Django 5.0.1 on 2025-12-12 06:30

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0006_booking_discount_amount_booking_gst_amount_and_more'),
        ('branches', '0001_initial'),
        ('customers', '0003_vehiclecolor_vehiclebrand_vehiclemodel'),
        ('services', '0004_simplify_vehicle_pricing'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=20, unique=True)),
                ('coupon_type', models.CharField(choices=[('percentage', 'Percentage Discount'), ('fixed', 'Fixed Amount Discount'), ('free_service', 'Free Service')], default='percentage', max_length=20)),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, help_text='Fixed discount amount', max_digits=10)),
                ('max_discount', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum discount amount (for percentage coupons)', max_digits=10, null=True)),
                ('min_order_value', models.DecimalField(decimal_places=2, default=0, help_text='Minimum order value to use this coupon', max_digits=10)),
                ('valid_from', models.DateTimeField(default=django.utils.timezone.now)),
                ('valid_until', models.DateTimeField()),
                ('usage_limit', models.PositiveIntegerField(default=1, help_text='How many times this coupon can be used (0 = unlimited)')),
                ('times_used', models.PositiveIntegerField(default=0)),
                ('is_single_user', models.BooleanField(default=False, help_text='Can only be used by the assigned customer')),
                ('is_membership_coupon', models.BooleanField(default=False)),
                ('is_global', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('used', 'Used'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('terms_conditions', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applicable_services', models.ManyToManyField(blank=True, related_name='applicable_coupons', to='services.servicepackage')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coupons', to='branches.branch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_coupons', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, help_text='Customer this coupon belongs to (for membership coupons)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coupons', to=settings.AUTH_USER_MODEL)),
                ('free_service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coupons', to='services.servicepackage')),
            ],
            options={
                'verbose_name': 'Coupon',
                'verbose_name_plural': 'Coupons',
                'db_table': 'coupons',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CouponUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_applied', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('used_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coupon_usages', to='bookings.booking')),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='memberships.coupon')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupon_usages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Coupon Usage',
                'verbose_name_plural': 'Coupon Usages',
                'db_table': 'coupon_usages',
                'ordering': ['-used_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomerMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('membership_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('vehicle_type', models.CharField(choices=[('hatchback', 'Hatchback'), ('sedan', 'Sedan'), ('suv', 'SUV')], default='sedan', max_length=20)),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gst_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('purchase_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pending Payment'), ('active', 'Active'), ('expired', 'Expired'), ('cancelled', 'Cancelled'), ('suspended', 'Suspended')], default='pending', max_length=20)),
                ('washes_used', models.PositiveIntegerField(default=0)),
                ('interior_cleanings_used', models.PositiveIntegerField(default=0)),
                ('payment_method', models.CharField(blank=True, max_length=50)),
                ('payment_reference', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_memberships', to='branches.branch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_memberships', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(help_text='Vehicle this membership is for', on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='customers.vehicle')),
            ],
            options={
                'verbose_name': 'Customer Membership',
                'verbose_name_plural': 'Customer Memberships',
                'db_table': 'customer_memberships',
                'ordering': ['-purchase_date'],
            },
        ),
        migrations.AddField(
            model_name='coupon',
            name='source_membership',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='generated_coupons', to='memberships.customermembership'),
        ),
        migrations.CreateModel(
            name='MembershipPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('tier', models.CharField(choices=[('bronze', 'Bronze'), ('silver', 'Silver'), ('gold', 'Gold'), ('platinum', 'Platinum'), ('diamond', 'Diamond')], default='silver', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('hatchback_price', models.DecimalField(decimal_places=2, default=0, help_text='Membership price for Hatchback owners', max_digits=10)),
                ('sedan_price', models.DecimalField(decimal_places=2, default=0, help_text='Membership price for Sedan owners', max_digits=10)),
                ('suv_price', models.DecimalField(decimal_places=2, default=0, help_text='Membership price for SUV owners', max_digits=10)),
                ('gst_applicable', models.BooleanField(default=True)),
                ('gst_rate', models.DecimalField(decimal_places=2, default=18.0, help_text='GST percentage', max_digits=5)),
                ('duration_value', models.PositiveIntegerField(default=12, help_text='Duration value (e.g., 12 for 12 months)')),
                ('duration_unit', models.CharField(choices=[('days', 'Days'), ('months', 'Months'), ('years', 'Years')], default='months', max_length=10)),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=0, help_text='Default discount percentage on services', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('free_washes_count', models.PositiveIntegerField(default=0, help_text='Number of free washes included')),
                ('free_interior_cleaning_count', models.PositiveIntegerField(default=0, help_text='Number of free interior cleaning included')),
                ('coupons_per_month', models.PositiveIntegerField(default=0, help_text='Number of coupons generated per month')),
                ('coupon_discount_percentage', models.DecimalField(decimal_places=2, default=10, help_text='Discount percentage for generated coupons', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('priority_booking', models.BooleanField(default=False, help_text='Priority booking for members')),
                ('is_active', models.BooleanField(default=True)),
                ('is_popular', models.BooleanField(default=False, help_text='Mark as popular/recommended plan')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_global', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='membership_plans', to='branches.branch')),
            ],
            options={
                'verbose_name': 'Membership Plan',
                'verbose_name_plural': 'Membership Plans',
                'db_table': 'membership_plans',
                'ordering': ['display_order', 'tier'],
            },
        ),
        migrations.CreateModel(
            name='MembershipBenefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('benefit_type', models.CharField(choices=[('free_service', 'Free Service'), ('discount', 'Discount'), ('priority', 'Priority Access'), ('addon', 'Free Add-on'), ('other', 'Other Benefit')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('service_count', models.PositiveIntegerField(default=0, help_text='Number of times this service is free')),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('is_active', models.BooleanField(default=True)),
                ('service_package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='membership_benefits', to='services.servicepackage')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='benefits', to='memberships.membershipplan')),
            ],
            options={
                'db_table': 'membership_benefits',
                'ordering': ['benefit_type', 'title'],
            },
        ),
        migrations.AddField(
            model_name='customermembership',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer_memberships', to='memberships.membershipplan'),
        ),
        migrations.CreateModel(
            name='MembershipCouponGeneration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.PositiveIntegerField()),
                ('year', models.PositiveIntegerField()),
                ('coupons_generated', models.PositiveIntegerField(default=0)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupon_generations', to='memberships.customermembership')),
            ],
            options={
                'db_table': 'membership_coupon_generations',
                'ordering': ['-year', '-month'],
                'unique_together': {('membership', 'month', 'year')},
            },
        ),
    ]
