# Generated by Django 5.0.1 on 2025-12-18 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membershipplan',
            name='hatchback_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Membership price for Hatchback owners', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='membershipplan',
            name='sedan_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Membership price for Sedan owners', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='membershipplan',
            name='suv_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Membership price for SUV owners', max_digits=10, null=True),
        ),
    ]
