# Generated by Django 5.0.1 on 2025-12-20 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0002_alter_membershipplan_hatchback_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='source_benefit',
            field=models.ForeignKey(blank=True, help_text='The membership benefit this coupon was generated from', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_coupons', to='memberships.membershipbenefit'),
        ),
        migrations.AddField(
            model_name='membershipbenefit',
            name='coupon_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of coupons to generate for this benefit (0 = no coupons, use direct counter)'),
        ),
        migrations.AddField(
            model_name='membershipbenefit',
            name='discount_fixed_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Fixed discount amount (e.g., ₹100 OFF)', max_digits=10),
        ),
        migrations.AddField(
            model_name='membershipbenefit',
            name='is_one_time',
            field=models.BooleanField(default=False, help_text='Can only be used once (e.g., First wash 50% OFF)'),
        ),
        migrations.CreateModel(
            name='MembershipBenefitUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_coupons_allocated', models.PositiveIntegerField(default=0, help_text='Total number of coupons allocated for this benefit')),
                ('coupons_used', models.PositiveIntegerField(default=0, help_text='Number of coupons already used')),
                ('is_one_time', models.BooleanField(default=False, help_text='This benefit can only be used once')),
                ('has_been_used', models.BooleanField(default=False, help_text='Whether this one-time benefit has been used')),
                ('first_used_at', models.DateTimeField(blank=True, help_text='When this benefit was first used', null=True)),
                ('last_used_at', models.DateTimeField(blank=True, help_text='When this benefit was last used', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('benefit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='memberships.membershipbenefit')),
                ('customer_membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='benefit_usages', to='memberships.customermembership')),
            ],
            options={
                'verbose_name': 'Membership Benefit Usage',
                'verbose_name_plural': 'Membership Benefit Usages',
                'db_table': 'membership_benefit_usages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='coupon',
            name='benefit_usage',
            field=models.ForeignKey(blank=True, help_text='The benefit usage record this coupon belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='generated_coupons', to='memberships.membershipbenefitusage'),
        ),
        migrations.AddIndex(
            model_name='membershipbenefitusage',
            index=models.Index(fields=['customer_membership', 'benefit'], name='membership__custome_a6a801_idx'),
        ),
        migrations.AddIndex(
            model_name='membershipbenefitusage',
            index=models.Index(fields=['customer_membership', 'has_been_used'], name='membership__custome_ce8ec6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='membershipbenefitusage',
            unique_together={('customer_membership', 'benefit')},
        ),
    ]
