# Generated by Django 5.0.1 on 2025-12-20 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0003_coupon_source_benefit_membershipbenefit_coupon_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='applicable_categories',
            field=models.JSONField(blank=True, default=list, help_text='Service categories this coupon applies to (e.g., ["wash", "polish"]). Leave empty for universal coupons.'),
        ),
        migrations.AddField(
            model_name='membershipbenefit',
            name='applicable_categories',
            field=models.JSONField(blank=True, default=list, help_text='Service categories this benefit applies to (e.g., ["wash", "polish"]). Leave empty for universal benefits.'),
        ),
    ]
