# Generated by Django 5.0.1 on 2026-02-06 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        ('memberships', '0004_coupon_applicable_categories_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coupons', to='companies.company'),
        ),
        migrations.AddField(
            model_name='customermembership',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_memberships', to='companies.company'),
        ),
        migrations.AddField(
            model_name='membershipbenefit',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='membership_benefits', to='companies.company'),
        ),
        migrations.AddField(
            model_name='membershipplan',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='membership_plans', to='companies.company'),
        ),
        migrations.AlterUniqueTogether(
            name='membershipplan',
            unique_together={('company', 'name')},
        ),
    ]
