# Generated by Django 5.0.1 on 2025-12-02 03:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_booking_branch'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='check_in_notes',
            field=models.TextField(blank=True, help_text='Notes from check-in process', null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='checked_in_by',
            field=models.ForeignKey(blank=True, help_text='Staff member who checked in the vehicle', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checked_in_bookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='booking',
            name='initial_damages',
            field=models.TextField(blank=True, help_text='Minor damages noted at check-in', null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='initial_photos',
            field=models.JSONField(blank=True, default=list, help_text='Initial vehicle photos taken at check-in'),
        ),
        migrations.AddField(
            model_name='booking',
            name='vehicle_arrived_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when vehicle arrived at branch', null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('vehicle_arrived', 'Vehicle Arrived'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
