# Generated by Django 5.0.1 on 2025-12-19 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_booking_discount_amount_booking_gst_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='vehicle_type',
            field=models.CharField(choices=[('hatchback', 'Hatchback'), ('sedan', 'Sedan'), ('suv', 'SUV'), ('bike', 'Bike')], default='sedan', help_text='Vehicle type for determining service price', max_length=20),
        ),
    ]
