# Generated by Django 5.0.1 on 2025-12-20 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0007_alter_booking_vehicle_type'),
        ('memberships', '0003_coupon_source_benefit_membershipbenefit_coupon_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='memberships.coupon'),
        ),
    ]
