# Generated by Django 5.0.1 on 2026-01-01 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0009_alter_booking_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_datetime',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('vehicle_arrived', 'Vehicle Arrived'), ('assigned_to_fm', 'Assigned to FM'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('assigned_to_applicator', 'Assigned to Applicator'), ('work_in_progress', 'Work in Progress'), ('work_completed', 'Work Completed'), ('final_qc_pending', 'Final QC Pending'), ('final_qc_passed', 'Final QC Passed'), ('final_qc_failed', 'Final QC Failed'), ('floor_manager_final_qc_confirmed', 'Floor Manager Final QC Confirmed'), ('customer_approval_pending', 'Customer Approval Pending'), ('customer_approved', 'Customer Approved'), ('customer_revision_requested', 'Customer Revision Requested'), ('ready_for_billing', 'Ready for Billing'), ('billed', 'Billed'), ('ready_for_delivery', 'Ready for Delivery'), ('delivered', 'Delivered'), ('closed', 'Closed')], db_index=True, default='pending', max_length=35),
        ),
    ]
