# Generated by Django 5.0.1 on 2026-02-03 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0011_add_workflow_statuses'),
        ('branches', '0003_servicebay'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='assigned_bay',
            field=models.ForeignKey(blank=True, help_text='Physical bay assigned for this service', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='branches.servicebay'),
        ),
    ]
