# Generated by Django 5.0.1 on 2026-02-04 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0012_booking_assigned_bay'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='referral_code_used',
            field=models.CharField(blank=True, help_text='Referral code used for this booking (only for first booking)', max_length=50, null=True),
        ),
    ]
