# Generated by Django 5.0.1 on 2026-02-06 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0013_booking_referral_code_used'),
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='companies.company'),
        ),
    ]
