# Generated by Django 5.0.1 on 2026-02-26 04:00

import django.db.models.deletion
from django.db import migrations, models


def copy_package_to_m2m(apps, schema_editor):
    """Copy the old single 'package' FK value into the new 'packages' M2M and primary_package."""
    Booking = apps.get_model('bookings', 'Booking')
    for booking in Booking.objects.exclude(primary_package__isnull=True):
        booking.packages.add(booking.primary_package)


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0014_booking_company'),
        ('services', '0011_update_unique_constraint_include_company'),
    ]

    operations = [
        # Step 1: Add the new fields (primary_package FK and packages M2M)
        migrations.AddField(
            model_name='booking',
            name='primary_package',
            field=models.ForeignKey(
                blank=True,
                help_text='Deprecated: use packages M2M instead',
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='primary_bookings',
                to='services.servicepackage',
            ),
        ),
        migrations.AddField(
            model_name='booking',
            name='packages',
            field=models.ManyToManyField(
                blank=True,
                help_text='One or more service packages for this booking',
                related_name='bookings',
                to='services.servicepackage',
            ),
        ),
        # Step 2: Copy old package FK → primary_package, then populate M2M
        # First, copy the existing 'package' value into 'primary_package' via raw SQL
        migrations.RunSQL(
            sql="UPDATE bookings SET primary_package_id = package_id WHERE package_id IS NOT NULL",
            reverse_sql=migrations.RunSQL.noop,
        ),
        # Step 3: Run Python data migration to populate the M2M table
        migrations.RunPython(copy_package_to_m2m, reverse_code=migrations.RunPython.noop),
        # Step 4: Remove the old 'package' FK
        migrations.RemoveField(
            model_name='booking',
            name='package',
        ),
    ]
