# Generated by Django 5.0.1 on 2026-02-06 17:14

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(help_text='Full domain or subdomain (e.g., k3car.autoaicare.com)', max_length=255, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_domain', message='Enter a valid domain name', regex='^[a-z0-9]([a-z0-9\\-]{0,61}[a-z0-9])?(\\.[a-z0-9]([a-z0-9\\-]{0,61}[a-z0-9])?)*$')])),
                ('subdomain', models.CharField(blank=True, db_index=True, help_text='Subdomain only (e.g., k3car)', max_length=63)),
                ('is_primary', models.BooleanField(default=False, help_text='Primary domain for this company')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this domain is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(help_text='Company this domain belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='companies.company')),
            ],
            options={
                'verbose_name': 'Company Domain',
                'verbose_name_plural': 'Company Domains',
                'db_table': 'company_domains',
                'ordering': ['-is_primary', 'domain'],
                'indexes': [models.Index(fields=['subdomain', 'is_active'], name='company_dom_subdoma_7f50a2_idx'), models.Index(fields=['domain', 'is_active'], name='company_dom_domain_8f95b8_idx')],
            },
        ),
    ]
