# Generated by Django 5.0.1 on 2026-02-12 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_add_domain_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysettings',
            name='enable_whatsapp_notifications',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='whatsapp_business_phone',
            field=models.CharField(blank=True, help_text="Company's WhatsApp Business phone number", max_length=20),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='whatsapp_credentials',
            field=models.JSONField(blank=True, default=dict, help_text='Encrypted WhatsApp API credentials: {provider, access_token, phone_number_id, business_account_id}'),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='whatsapp_provider',
            field=models.CharField(blank=True, choices=[('meta', 'Meta Cloud API'), ('twilio', 'Twilio'), ('messagebird', 'MessageBird')], default='meta', max_length=20),
        ),
    ]
