# Generated by Django 5.0.1 on 2026-02-12 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_companysettings_enable_whatsapp_notifications_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysettings',
            name='whatsapp_mode',
            field=models.CharField(choices=[('manual', 'Manual (Click-to-Send)'), ('api', 'Automated (Cloud API)')], default='manual', help_text='WhatsApp sending mode: manual (wa.me links) or automated (Cloud API)', max_length=10),
        ),
    ]
