# Generated by Django 5.0.1 on 2026-03-14 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_companysettings_whatsapp_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysettings',
            name='wp_api_key',
            field=models.CharField(blank=True, help_text='API Key generated by the WP Messaging Gateway', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='wp_url',
            field=models.URLField(blank=True, help_text='Base URL of the WP Messaging Gateway (e.g., http://localhost:8001)', null=True),
        ),
    ]
